package com.other;

import java.util.Arrays;
import java.util.List;

public enum Synonym {
    enum_1("复杂的", "adj.", Arrays.asList("complex", "complicated")),
    enum_2("生病的", "adj.", Arrays.asList("ill", "sick")),
    enum_3("会议", "n.", Arrays.asList("meeting", "conference", "seminar", "session")),
    enum_4("可能地", "adv.", Arrays.asList("probably", "perhaps", "maybe")),
    enum_5("妥协", "n.", Arrays.asList("concession", "compromise")),
    enum_6("努力", "v.", Arrays.asList("effort", "endeavour", "strive", "struggle")),
    enum_16("小偷", "n.", Arrays.asList("thief", "pickpocket")),
    enum_18("衣服", "n.", Arrays.asList("clothes", "clothing")),
    enum_20("盘子", "n.", Arrays.asList("dish", "plate")),
    enum_22("宣布", "v.", Arrays.asList("announce", "declare", "proclaim", "pronounce")),
    enum_24("裁判", "n.", Arrays.asList("judge", "judgement", "referee")),
    enum_26("特别的", "adj.", Arrays.asList("special", "especial", "particular", "specific", "exceptive", "exceptional")),
    enum_28("立即的", "adj.", Arrays.asList("prompt", "instant", "immediate")),
    enum_30("诚实的", "adj.", Arrays.asList("honest", "honorable")),
    enum_32("战斗", "n.", Arrays.asList("battle", "combat", "fight")),
    enum_34("里面的", "adj.", Arrays.asList("inner", "inside", "inward", "internal", "interior", "intrinsic")),
    enum_35("外面的", "adj.", Arrays.asList("outer", "outside", "outward", "external", "exterior")),
    enum_36("人口", "n.", Arrays.asList("populace", "population", "populous")),
    enum_38("检查", "v.", Arrays.asList("check", "examine", "inspect")),
    enum_39("垃圾", "n.", Arrays.asList("waste", "garbage", "rubbish", "junk")),
    enum_40("方法", "n.", Arrays.asList("method", "way", "means")),
    enum_42("获得", "v.", Arrays.asList("gain", "attain", "get", "obtain")),
    enum_45("评估", "v.", Arrays.asList("estimate", "assess")),
    enum_46("街道", "n.", Arrays.asList("street", "avenue")),
    enum_48("同意", "v.", Arrays.asList("agree", "consent")),
    enum_49("国会", "n.", Arrays.asList("parliament", "congress")),
    enum_50("尝试(做)", "v.", Arrays.asList("try", "attempt", "have a smack at sth")),
    enum_51("发明", "v.", Arrays.asList("invent", "devise")),
    enum_52("拉", "v.", Arrays.asList("pull", "draw", "drag")),
    enum_53("决定", "n.", Arrays.asList("determination", "decision")),
    enum_54("识别", "v.", Arrays.asList("recognize", "identify", "distinguish")),
    enum_61("聪明的", "adj.", Arrays.asList("intellectual", "intelligent")),
    enum_63("精确的", "adj.", Arrays.asList("accurate", "exact", "precise")),
    enum_65("旅行", "n.", Arrays.asList("journey", "travel", "tour", "trip")),
    enum_67("基础", "n.", Arrays.asList("base", "basic", "basis", "foundation", "element")),
    enum_69("情感", "n.", Arrays.asList("emotion", "mood")),
    enum_71("扩大", "v.", Arrays.asList("extend", "expand", "enlarge")),
    enum_73("坚持", "v.", Arrays.asList("insist", "persist")),
    enum_75("打扫", "v.", Arrays.asList("sweep", "clean")),
    enum_77("在旁面", "prep.", Arrays.asList("nearby", "beside")),
    enum_79("边界", "n.", Arrays.asList("border", "frontier")),
    enum_81("恢复", "v", Arrays.asList("recover", "restore")),
    enum_83("明显地", "adv.", Arrays.asList("apparently", "obviously")),
    enum_85("优秀的", "adj.", Arrays.asList("extraordinary", "excellent", "outstanding")),
    enum_87("愚蠢的", "adj.", Arrays.asList("dumb", "stupid")),
    enum_89("最终的", "adj.", Arrays.asList("final", "eventual", "ultima")),
    enum_91("在...下面", "prep.", Arrays.asList("under", "below")),
    enum_93("建议", "v.", Arrays.asList("advise", "recommend")),
    enum_96("潮湿的", "adj.", Arrays.asList("wet", "damp", "humid")),
    enum_98("推论（出）", "v.", Arrays.asList("conclude", "deduce", "infer")),
    enum_100("命运", "n.", Arrays.asList("fortune", "fate")),
    enum_102("名声", "n.", Arrays.asList("reputation", "fame")),
    enum_104("飞机", "n.", Arrays.asList("airplane", "plane", "aircraft", "flight")),
    enum_107("巨大的", "adj.", Arrays.asList("huge", "immense", "giant", "enormous")),
    enum_108("病", "n.", Arrays.asList("disease", "illness", "condition", "disorder")),
    enum_110("完成", "v.", Arrays.asList("complete", "achieve")),
    enum_111("痛", "n.", Arrays.asList("pain", "ache")),
    enum_112("细节", "n.", Arrays.asList("detail", "particular", "specific")),
    enum_114("责怪", "v.", Arrays.asList("accuse", "blame")),
    enum_116("理解", "n.", Arrays.asList("comprehension", "grasp")),
    enum_118("信仰", "n.", Arrays.asList("faith", "belief")),
    enum_120("忽略", "v.", Arrays.asList("neglect", "ignore", "overlook")),
    enum_122("安排", "v.", Arrays.asList("arrange", "schedule", "")),
    enum_124("路线", "n.", Arrays.asList("line", "route")),
    enum_126("百分比", "n.", Arrays.asList("percent", "percentage", "percentum")),
    enum_128("视野", "n.", Arrays.asList("view", "sight", "vision")),
    enum_130("相反的", "adj", Arrays.asList("reverse", "adverse", "converse", "opposite", "contrary")),
    enum_132("宏伟壮丽的", "adj", Arrays.asList("magnificent", "splendid")),
    enum_133("劝告", "v.", Arrays.asList("advise", "counsel")),
    enum_135("组织", "v.", Arrays.asList("organize", "structure")),
    enum_137("揭露", "v.", Arrays.asList("expose", "reveal")),
    enum_139("仁慈的", "adj", Arrays.asList("merciful", "gracious")),
    enum_141("承认", "v.", Arrays.asList("admit", "acknowledge")),
    enum_143("混乱", "n.", Arrays.asList("disorder", "chaos")),
    enum_145("可怕的", "adj", Arrays.asList("terrible", "dreadful", "frightful")),
    enum_147("保护", "v.", Arrays.asList("protect", "preserve", "conserve")),
    enum_149("延期", "v.", Arrays.asList("delay", "postpone")),
    enum_151("群", "n.", Arrays.asList("group", "flock", "crowd")),
    enum_154("聪明的", "adj.", Arrays.asList("smart", "bright", "intelligent", "brainy", "clever")),
    enum_155("宽度", "n.", Arrays.asList("width", "breadth")),
    enum_156("高度", "n.", Arrays.asList("height", "altitude")),
    enum_157("自行车", "n.", Arrays.asList("bicycle", "bike")),
    enum_158("球拍", "n.", Arrays.asList("racket", "bat")),
    enum_160("争论", "v.", Arrays.asList("argue", "dispute")),
    enum_161("抛弃", "v.", Arrays.asList("abandon", "desert")),
    enum_162("决定", "v.", Arrays.asList("determine", "decide")),
    enum_163("运送", "v.", Arrays.asList("transport", "convey")),
    enum_164("价格", "n.", Arrays.asList("price", "cost")),
    enum_165("谈话", "n.", Arrays.asList("conversation", "talk")),
    enum_166("禁止", "v.", Arrays.asList("forbid", "prohibit")),
    enum_167("绝望的", "adj.", Arrays.asList("desperate", "hopeless")),
    enum_168("诚实的", "adj.", Arrays.asList("honest", "honourable")),
    enum_169("管理", "n.", Arrays.asList("management", "administration")),
    enum_171("结果", "n.", Arrays.asList("result", "consequence")),
    enum_173("参加", "v.", Arrays.asList("attend", "join", "participate")),
    enum_175("调查", "v.", Arrays.asList("inquire", "investigate")),
    enum_177("运气", "n", Arrays.asList("luck", "fortune")),
    enum_179("命运", "n.", Arrays.asList("fate", "destiny", "fortune")),
    enum_181("估计", "v.", Arrays.asList("estimate", "compute")),
    enum_183("电影院", "n.", Arrays.asList("theater", "cinema")),
    enum_185("减少", "v", Arrays.asList("decline", "decrease", "reduce")),
    enum_187("货物", "n.", Arrays.asList("goods", "cargo")),
    enum_189("咒骂", "v.", Arrays.asList("curse", "rail")),
    enum_191("舒适的", "adj.", Arrays.asList("comfortable", "cozy")),
    enum_193("凝视", "v.", Arrays.asList("gaze", "stare")),
    enum_195("临时的", "adj.", Arrays.asList("temporary", "momentary")),
    enum_197("魔术", "n.", Arrays.asList("magic", "conjure")),
    enum_198("装饰", "v.", Arrays.asList("decorate", "upholster")),
    enum_199("招待", "v.", Arrays.asList("treat", "entertain")),
    enum_200("瓷器", "n.", Arrays.asList("pottery", "ceram", "porcelain")),
    enum_201("雕刻", "v.", Arrays.asList("carve", "sculpture")),
    enum_202("宽广的", "adj.", Arrays.asList("broad", "expansive", "wide", "spacious")),
    enum_203("超过", "v.", Arrays.asList("exceed","excess", "surpass", "overrun")),
    enum_204("高兴", "v.", Arrays.asList("pleasure", "rejoice", "delight", "cheer", "joy")),
    enum_205("赞助商", "n.", Arrays.asList("sponsor", "patron", "delight", "cheer", "joy")),
    enum_206("商标", "n.", Arrays.asList("logo", "brand", "trademark")),
    enum_207("决定", "v.", Arrays.asList("determine", "decide", "resolve")),
    enum_208("敌人", "n.", Arrays.asList("enemy", "foe")),
    enum_209("尸体", "n.", Arrays.asList("corpse", "cadaver")),
    enum_210("边界", "n.", Arrays.asList("edge", "rim", "border")),
    enum_211("休息", "n.", Arrays.asList("rest", "break", "respite", "repose")),
    enum_212("古怪的", "adj.", Arrays.asList("weird", "bizarre")),
    enum_213("注意", "v.", Arrays.asList("attend", "notice", "heed")),
    enum_214("检查", "v.", Arrays.asList("check", "inspect", "examine")),
    enum_215("姿势", "n.", Arrays.asList("posture", "gesture", "attitude", "manner")),
    enum_216("轮廓", "n.", Arrays.asList("figure", "silhouette")),
    enum_217("走", "v.", Arrays.asList("go", "hick", "stroll", "wander", "walk", "move", "track", "wend", "pad", "step")),
    enum_218("到达", "v.", Arrays.asList("arrive", "reach", "get in")),
    enum_219("抑制", "v.", Arrays.asList("restrain", "stall", "control", "stop")),
    enum_220("入侵", "v.", Arrays.asList("invade", "intrude")),
    enum_221("分开", "v.", Arrays.asList("part", "segregate", "detach", "disjoin", "separate", "isolate", "insulate")),
    enum_222("有关残疾的", "adj.", Arrays.asList("blind", "deaf", "dumb", "lame", "crippled", "mute", "paralyzed", "stupid", "handicapped", "disabled")),
    enum_223("担架", "n.", Arrays.asList("litter", "stretcher")),
    enum_224("末尾", "n.", Arrays.asList("tail", "end", "stern")),
    enum_225("裂缝", "n.", Arrays.asList("crack", "flaw", "tear", "gap", "slit")),
    enum_226("擦拭", "v.", Arrays.asList("sponge", "wipe", "mop", "rub", "scrub")),
    enum_227("穿", "v.", Arrays.asList("wear", "clad", "put on", "dress")),
    enum_228("结束", "v.", Arrays.asList("terminate", "stop", "kill", "finish")),
    enum_229("倾斜", "v.", Arrays.asList("incline", "lean", "slant")),
    enum_230("五官的", "adj.", Arrays.asList("ocular", "aural", "nasal", "oral", "lingual", "dental", "facial")),
    enum_231("缺点", "n.", Arrays.asList("shortcoming", "defect", "weakness", "drawback", "disadvantage", "flaw")),
    enum_232("面", "n.", Arrays.asList("side（对立面）", "aspect（分析层面）", "facet（立体多面）")),
    enum_233("改善", "v.", Arrays.asList("improve", "amend")),
    enum_234("怀疑", "v.", Arrays.asList("suspect", "doubt")),
    enum_235("分娩", "v.", Arrays.asList("bear", "deliver", "labour")),
    enum_236("婴儿", "n.", Arrays.asList("infant", "baby")),
    enum_237("减轻", "v.", Arrays.asList("relieve", "alleviate")),
    enum_238("财政的", "adj.", Arrays.asList("financial（金融财务）", "monetary（货币）", "economic（经济）")),
    enum_239("好运的", "adj.", Arrays.asList("lucky", "fortunate", "blessed")),
    enum_240("养育", "v.", Arrays.asList("foster", "rear", "bring up", "nurture")),
    enum_241("障碍", "n.", Arrays.asList("barrier", "hurdle", "obstacle")),
    enum_242("想要", "v.", Arrays.asList("want", "demand")),
    enum_243("使痛苦", "v.", Arrays.asList("afflict", "distress")),
    enum_244("新人", "n.", Arrays.asList("freshman","newcomer")),
    enum_245("察觉", "v.", Arrays.asList("be aware of","perceive", "sense")),
    enum_246("压力", "n.", Arrays.asList("stress","pressure")),
    enum_247("证明", "v.", Arrays.asList("prove","testify")),
    enum_248("敏感的", "adj.", Arrays.asList("sensitive", "susceptible")),
    enum_249("看起来", "link.", Arrays.asList("seem", "appear", "look")),
    enum_250("树枝", "n.", Arrays.asList("bough", "branch")),
    enum_251("建造", "v.", Arrays.asList("build", "construct", "make", "establish", "create")),














    ;

    String chinese;
    String pos;
    List<String> engList;

    Synonym(String chinese, String pos, List<String> engList) {
        this.chinese = chinese;
        this.pos = pos;
        this.engList = engList;
    }


}
