package com.other;

import java.util.Arrays;
import java.util.List;

public enum Synonym {
    enum_1("复杂的", "adj.", Arrays.asList("complex", "complicated")),
    enum_2("生病的", "adj.", Arrays.asList("ill", "sick")),
    enum_3("会议", "n.", Arrays.asList("meeting", "conference", "seminar", "session", "forum")),
    enum_4("可能地", "adv.", Arrays.asList("probably", "perhaps", "maybe")),
    enum_5("妥协", "n.", Arrays.asList("concession", "compromise")),
    enum_6("努力", "v.", Arrays.asList("effort", "endeavour", "strive", "struggle")),
    enum_16("小偷", "n.", Arrays.asList("thief", "pickpocket")),
    enum_18("衣服", "n.", Arrays.asList("clothes", "clothing")),
    enum_20("盘子", "n.", Arrays.asList("dish", "plate")),
    enum_22("宣布", "v.", Arrays.asList("announce", "declare", "proclaim", "pronounce", "report", "post")),
    enum_24("裁判", "n.", Arrays.asList("judge", "judgement", "referee")),
    enum_26("特别的", "adj.", Arrays.asList("special", "especial", "particular", "specific", "exceptive", "exceptional", "given")),
    enum_28("立即的", "adj.", Arrays.asList("prompt", "instant", "immediate", "instantaneous")),
    enum_30("诚实的", "adj.", Arrays.asList("honest", "honorable")),
    enum_32("战斗", "n.", Arrays.asList("battle", "combat", "fight")),
    enum_34("里面的", "adj.", Arrays.asList("inner", "inside", "inward", "internal", "interior", "intrinsic")),
    enum_35("外面的", "adj.", Arrays.asList("outer", "outside", "outward", "external", "exterior")),
    enum_36("人口", "n.", Arrays.asList("populace", "population", "populous")),
    enum_38("检查", "v.", Arrays.asList("check", "examine", "inspect")),
    enum_39("垃圾", "n.", Arrays.asList("waste", "garbage", "rubbish", "junk", "refuse", "landfill")),
    enum_40("方法", "n.", Arrays.asList("method", "way", "means", "manner", "approach")),
    enum_42("获得", "v.", Arrays.asList("gain", "attain", "get", "obtain", "earn")),
    enum_45("评估", "v.", Arrays.asList("estimate", "assess")),
    enum_46("街道", "n.", Arrays.asList("street", "avenue")),
    enum_48("同意", "v.", Arrays.asList("agree", "consent")),
    enum_49("国会", "n.", Arrays.asList("parliament", "congress")),
    enum_50("尝试(做)", "v.", Arrays.asList("try", "attempt", "have a smack at sth")),
    enum_51("发明", "v.", Arrays.asList("invent", "devise")),
    enum_52("拉", "v.", Arrays.asList("pull", "draw", "drag")),
    enum_53("决定（心）", "n.", Arrays.asList("determination", "decision", "resolve")),
    enum_54("识别", "v.", Arrays.asList("recognize", "identify", "distinguish")),
    enum_61("聪明的", "adj.", Arrays.asList("intellectual", "intelligent")),
    enum_63("精确的", "adj.", Arrays.asList("accurate", "exact", "precise")),
    enum_65("旅行", "n.", Arrays.asList("journey", "travel", "tour", "trip")),
    enum_67("基础", "n.", Arrays.asList("base", "basic", "basis", "foundation", "element", "essential")),
    enum_69("情感", "n.", Arrays.asList("emotion", "mood")),
    enum_71("扩大", "v.", Arrays.asList("extend", "expand", "enlarge")),
    enum_73("坚持", "v.", Arrays.asList("insist", "persist")),
    enum_75("打扫", "v.", Arrays.asList("sweep", "clean")),
    enum_77("在旁面", "prep.", Arrays.asList("nearby", "beside")),
    enum_79("边界", "n.", Arrays.asList("border", "frontier")),
    enum_81("恢复", "v", Arrays.asList("recover", "restore")),
    enum_83("明显地", "adv.", Arrays.asList("apparently", "obviously")),
    enum_85("优秀的", "adj.", Arrays.asList("extraordinary", "excellent", "outstanding", "superb", "great", "prominent")),
    enum_87("愚蠢的", "adj.", Arrays.asList("dumb", "stupid")),
    enum_89("最终的", "adj.", Arrays.asList("final", "eventual", "ultima")),
    enum_91("在...下面", "prep.", Arrays.asList("under", "below", "beneath")),
    enum_93("建议", "v.", Arrays.asList("advise", "recommend", "propose", "suggest")),
    enum_96("潮湿的", "adj.", Arrays.asList("wet", "damp", "humid")),
    enum_98("推论（出）", "v.", Arrays.asList("conclude", "deduce", "infer")),
    enum_100("命运", "n.", Arrays.asList("fortune", "fate")),
    enum_102("名声", "n.", Arrays.asList("reputation", "fame")),
    enum_104("飞机", "n.", Arrays.asList("airplane", "plane", "aircraft", "flight")),
    enum_107("巨大的", "adj.", Arrays.asList("huge", "immense", "giant", "enormous", "gigantic", "large")),
    enum_108("病", "n.", Arrays.asList("disease", "illness", "condition", "disorder")),
    enum_110("完成", "v.", Arrays.asList("complete", "finish", "fulfil", "achieve", "accomplish")),
    enum_111("痛", "n.", Arrays.asList("pain", "ache")),
    enum_112("细节", "n.", Arrays.asList("detail", "particular", "specific")),
    enum_114("责怪", "v.", Arrays.asList("accuse", "blame")),
    enum_116("理解", "n.", Arrays.asList("understand", "comprehension", "grasp", "assimilate")),
    enum_118("信仰", "n.", Arrays.asList("faith", "belief")),
    enum_120("忽略", "v.", Arrays.asList("neglect", "ignore", "overlook")),
    enum_122("安排", "v.", Arrays.asList("arrange", "schedule", "")),
    enum_124("路线", "n.", Arrays.asList("line", "route")),
    enum_126("百分比", "n.", Arrays.asList("percent", "percentage", "percentum")),
    enum_128("视野", "n.", Arrays.asList("view", "sight", "vision")),
    enum_130("相反的", "adj", Arrays.asList("reverse", "adverse", "converse", "opposite", "contrary")),
    enum_132("宏伟壮丽的", "adj", Arrays.asList("magnificent", "splendid")),
    enum_133("劝告", "v.", Arrays.asList("advise", "counsel")),
    enum_135("组织", "v.", Arrays.asList("organize", "structure")),
    enum_137("揭露", "v.", Arrays.asList("expose", "reveal")),
    enum_139("仁慈的", "adj", Arrays.asList("merciful", "gracious")),
    enum_141("承认", "v.", Arrays.asList("admit", "acknowledge")),
    enum_143("混乱", "n.", Arrays.asList("disorder", "chaos")),
    enum_145("可怕的", "adj", Arrays.asList("terrible", "dreadful", "frightful", "formidable", "terrified")),
    enum_147("保护", "v.", Arrays.asList("protect", "preserve", "conserve", "guard", "safeguard")),
    enum_149("延期", "v.", Arrays.asList("delay", "postpone")),
    enum_151("群", "n.", Arrays.asList("group", "flock", "crowd")),
    enum_154("聪明的", "adj.", Arrays.asList("smart", "bright", "intelligent", "brainy", "clever")),
    enum_155("宽度", "n.", Arrays.asList("width", "breadth")),
    enum_156("高度", "n.", Arrays.asList("height", "altitude")),
    enum_157("自行车", "n.", Arrays.asList("bicycle", "bike")),
    enum_158("球拍", "n.", Arrays.asList("racket", "bat")),
    enum_160("争论", "v.", Arrays.asList("argue", "dispute")),
    enum_161("抛弃", "v.", Arrays.asList("abandon", "desert")),
    enum_162("决定", "v.", Arrays.asList("determine", "decide")),
    enum_163("运送", "v.", Arrays.asList("transport", "convey")),
    enum_164("价格", "n.", Arrays.asList("price", "cost")),
    enum_165("谈话", "n.", Arrays.asList("conversation", "talk")),
    enum_166("禁止", "v.", Arrays.asList("forbid", "prohibit")),
    enum_167("绝望的", "adj.", Arrays.asList("desperate", "hopeless")),
    enum_168("诚实的", "adj.", Arrays.asList("honest", "honourable")),
    enum_169("管理", "n.", Arrays.asList("management", "administration")),
    enum_171("结果", "n.", Arrays.asList("result", "consequence")),
    enum_173("参加", "v.", Arrays.asList("attend", "join", "participate")),
    enum_175("调查", "v.", Arrays.asList("inquire", "investigate")),
    enum_177("运气", "n", Arrays.asList("luck", "fortune")),
    enum_179("命运", "n.", Arrays.asList("fate", "destiny", "fortune")),
    enum_181("估计", "v.", Arrays.asList("estimate", "compute")),
    enum_183("电影院", "n.", Arrays.asList("theater", "cinema")),
    enum_185("减少", "v", Arrays.asList("decline", "decrease", "reduce", "cut back")),
    enum_187("货物", "n.", Arrays.asList("goods", "cargo", "commodity")),
    enum_189("咒骂", "v.", Arrays.asList("curse", "rail")),
    enum_191("舒适的", "adj.", Arrays.asList("comfortable", "cozy")),
    enum_193("凝视", "v.", Arrays.asList("gaze", "stare")),
    enum_195("临时的", "adj.", Arrays.asList("temporary", "momentary")),
    enum_197("魔术", "n.", Arrays.asList("magic", "conjure")),
    enum_198("装饰", "v.", Arrays.asList("decorate", "upholster", "adorn")),
    enum_199("招待", "v.", Arrays.asList("treat", "entertain")),
    enum_200("瓷器", "n.", Arrays.asList("pottery", "ceram", "porcelain")),
    enum_201("雕刻", "v.", Arrays.asList("carve", "sculpture")),
    enum_202("宽广的", "adj.", Arrays.asList("broad", "expansive", "wide", "spacious")),
    enum_203("超过", "v.", Arrays.asList("exceed","excess", "surpass", "overrun")),
    enum_204("高兴", "v.", Arrays.asList("pleasure", "rejoice", "delight", "cheer", "joy")),
    enum_205("赞助商", "n.", Arrays.asList("sponsor", "patron", "delight", "cheer", "joy")),
    enum_206("商标", "n.", Arrays.asList("logo", "brand", "trademark")),
    enum_207("决定", "v.", Arrays.asList("determine", "decide", "resolve")),
    enum_208("敌人", "n.", Arrays.asList("enemy", "foe")),
    enum_209("尸体", "n.", Arrays.asList("corpse", "cadaver")),
    enum_210("边界", "n.", Arrays.asList("edge", "rim", "border", "verge")),
    enum_211("休息", "n.", Arrays.asList("rest", "break", "respite", "repose")),
    enum_212("古怪的", "adj.", Arrays.asList("weird", "bizarre", "queer")),
    enum_213("注意", "v.", Arrays.asList("attend", "notice", "heed")),
    enum_214("检查", "v.", Arrays.asList("check", "inspect", "examine")),
    enum_215("姿势", "n.", Arrays.asList("posture", "gesture", "attitude", "manner")),
    enum_216("轮廓", "n.", Arrays.asList("figure", "silhouette")),
    enum_217("走", "v.", Arrays.asList("go", "hick", "stroll", "wander", "walk", "move", "track", "wend", "pad", "step", "jog", "wander", "lounge")),
    enum_218("到达", "v.", Arrays.asList("arrive", "reach", "get in")),
    enum_219("抑制", "v.", Arrays.asList("restrain", "stall", "control", "stop")),
    enum_220("入侵", "v.", Arrays.asList("invade", "intrude")),
    enum_221("分开", "v.", Arrays.asList("part", "segregate", "detach", "disjoin", "separate", "isolate", "insulate")),
    enum_222("有关残疾的", "adj.", Arrays.asList("stupid","blind", "deaf", "dumb", "mute", "lame", "crippled", "", "paralyzed", "", "handicapped", "disabled", "dwarf")),
    enum_223("担架", "n.", Arrays.asList("litter", "stretcher")),
    enum_224("末尾", "n.", Arrays.asList("tail", "end", "stern")),
    enum_225("裂缝", "n.", Arrays.asList("crack", "flaw", "tear", "gap", "slit")),
    enum_226("擦拭", "v.", Arrays.asList("sponge", "wipe", "mop", "rub", "scrub")),
    enum_227("穿", "v.", Arrays.asList("wear", "clad", "put on", "dress", "don")),
    enum_228("结束", "v.", Arrays.asList("terminate", "stop", "kill", "finish", "closure")),
    enum_229("倾斜", "v.", Arrays.asList("incline", "lean", "slant")),
    enum_230("五官的", "adj.", Arrays.asList("ocular", "aural", "nasal", "oral", "lingual", "dental", "facial")),
    enum_231("缺点", "n.", Arrays.asList("shortcoming", "defect", "weakness", "drawback", "disadvantage", "flaw")),
    enum_232("面", "n.", Arrays.asList("side（对立面）", "aspect（分析层面）", "facet（立体多面）")),
    enum_233("改善", "v.", Arrays.asList("improve", "amend", "increase", "rise", "raise", "")),
    enum_234("怀疑", "v.", Arrays.asList("suspect", "doubt")),
    enum_235("分娩", "v.", Arrays.asList("bear", "deliver", "labour")),
    enum_236("婴儿", "n.", Arrays.asList("infant", "baby")),
    enum_237("减轻", "v.", Arrays.asList("relieve", "alleviate")),
    enum_238("财政的", "adj.", Arrays.asList("financial（金融财务）", "monetary（货币）", "economic（经济）")),
    enum_239("好运的", "adj.", Arrays.asList("lucky", "fortunate", "blessed")),
    enum_240("养育", "v.", Arrays.asList("foster", "rear", "bring up", "nurture")),
    enum_241("障碍", "n.", Arrays.asList("barrier", "hurdle", "obstacle")),
    enum_242("想要", "v.", Arrays.asList("want", "demand", "desire", "intend")),
    enum_243("使痛苦", "v.", Arrays.asList("afflict", "distress")),
    enum_244("新人", "n.", Arrays.asList("freshman","newcomer")),
    enum_245("察觉", "v.", Arrays.asList("be aware of","perceive", "sense")),
    enum_246("压力", "n.", Arrays.asList("stress","pressure")),
    enum_247("证明", "v.", Arrays.asList("prove", "testify", "certify")),
    enum_248("敏感的", "adj.", Arrays.asList("sensitive", "susceptible")),
    enum_249("看起来", "link.", Arrays.asList("seem", "appear", "look")),
    enum_250("树枝", "n.", Arrays.asList("bough", "branch")),
    enum_251("建造", "v.", Arrays.asList("build", "construct", "make", "establish", "create")),
    enum_252("上升", "v.", Arrays.asList("rise", "ascend", "surge")),
    enum_253("下降", "v.", Arrays.asList("fall", "descend", "drop")),
    enum_254("分割", "v.", Arrays.asList("slicing", "partition")),
    enum_255("公平的", "adj.", Arrays.asList("fair", "impartial", "disinterest")),
    enum_256("接近", "v.", Arrays.asList("access", "approach", "close in", "stalk")),
    enum_257("欺负", "v.", Arrays.asList("push sb. around", "bully")),
    enum_258("主权", "n.", Arrays.asList("dominion", "sovereignty")),
    enum_259("剥夺", "v.", Arrays.asList("deny", "deprive")),
    enum_260("羞辱", "v.", Arrays.asList("shame", "humiliate")),
    enum_261("利益", "n.", Arrays.asList("benefit", "interest", "profit")),
    enum_262("实际上", "adv.", Arrays.asList("virtually", "really", "in fact", "in practice")),
    enum_263("冲突", "v.", Arrays.asList("conflict", "collide")),
    enum_264("讨厌", "v.", Arrays.asList("hate", "abominate")),
    enum_265("杀死", "v.", Arrays.asList("kill", "murder", "slaughter", "massacre")),
    enum_266("打败", "v.", Arrays.asList("defeat", "overwhelm")),
    enum_267("合作", "v.", Arrays.asList("cooperate", "collaborate")),
    enum_268("抑制（限制进一步发展）", "v.", Arrays.asList("curb", "contain", "check")),
    enum_269("重新开始", "n.", Arrays.asList("restart", "resumption")),
    enum_270("联盟", "n.", Arrays.asList("coalition", "union", "alliance", "league")),
    enum_271("间隔的", "adj.", Arrays.asList("alternate", "intermittent")),
    enum_272("举", "v.", Arrays.asList("lift", "raise", "heave", "")),
    enum_273("威胁", "v.", Arrays.asList("threaten", "menace")),
    enum_274("刺", "n.", Arrays.asList("prick", "thorn")),
    enum_275("继续", "v.", Arrays.asList("continue", "go on", "resume", "pick up", "proceed")),
    enum_276("计划", "v.", Arrays.asList("plan", "formulate", "scheme", "intrigue")),
    enum_277("传播", "v.", Arrays.asList("spread", "transmit", "propagate", "")),
    enum_278("分散", "v.", Arrays.asList("scatter", "diffuse", "disperse")),
    enum_279("使严重", "v.", Arrays.asList("worsen", "complicate", "aggravate", "exacerbate", "deteriorate", "perplex")),
    enum_280("促进", "v.", Arrays.asList("help", "encourage", "serve to")),
    enum_281("离开", "v.", Arrays.asList("leave", "get out", "quit", "depart from")),
    enum_282("单独的", "adj.", Arrays.asList("alone", "solitary")),
    enum_283("疯狂的", "adj.", Arrays.asList("crazy", "frantic")),
    enum_284("旅馆", "n.", Arrays.asList("hotel", "inn")),
    enum_285("交易", "n.", Arrays.asList("trade", "deal", "bargain", "commerce")),
    enum_286("事情", "n.", Arrays.asList("affair", "event", "incident", "matter", "business", "things")),
    enum_287("可疑的", "adj.", Arrays.asList("suspectable", "dubious", "doubtful")),
    enum_288("找", "v.", Arrays.asList("find", "seek", "look for", "locate", "search")),
    enum_289("教堂", "n.", Arrays.asList("church", "chapel", "cathedral")),
    enum_290("匆忙的", "adj.", Arrays.asList("hurried", "hasty")),
    enum_291("撤退", "v.", Arrays.asList("withdraw", "retreat", "evacuate")),
    enum_292("伴侣", "n.", Arrays.asList("couple", "mate", "partner", "spouse")),
    enum_293("思考", "v.", Arrays.asList("think", "contemplate", "ponder", "deliberate", "dwell upon/on")),
    enum_294("统治", "v.", Arrays.asList("rule", "dominate", "predominate", "govern")),
    enum_295("主要的", "adj.", Arrays.asList("primary", "prime", "main", "major", "predominant", "central")),
    enum_296("神圣的", "adj.", Arrays.asList("holy", "sacred", "divine")),
    enum_297("救赎", "v.", Arrays.asList("redemption", "salvation")),
    enum_298("回想", "v.", Arrays.asList("remember", "retrospect")),
    enum_299("吸引", "v.", Arrays.asList("attract", "fascinate", "allure")),
    enum_300("精美的", "adj.", Arrays.asList("delicate", "exquisite")),
    enum_301("花", "n.", Arrays.asList("flower", "blossom")),
    enum_302("诱惑", "v.", Arrays.asList("attempt", "lure")),
    enum_303("允许", "v.", Arrays.asList("allow", "permit", "clear")),
    enum_304("命令", "v.", Arrays.asList("command", "order", "mandate")),
    enum_305("污染", "v.", Arrays.asList("pollute", "contaminate", "blur")),
    enum_306("灾难", "n.", Arrays.asList("disaster", "catastrophe", "misfortune")),
    enum_307("反对", "v.", Arrays.asList("oppose", "protest", "object", "be against to", "boycott", "disapprove")),
    enum_308("伪装", "v.", Arrays.asList("pretend", "disguise", "veil")),
    enum_309("处理", "v.", Arrays.asList("deal with", "handle", "address")),
    enum_310("丰富的", "adj.", Arrays.asList("abundant", "ample", "sufficient")),
    enum_311("批准", "v.", Arrays.asList("approve", "authorize")),
    enum_312("位置", "n.", Arrays.asList("site", "location", "place","position","locality")),
    enum_313("连续的", "adj.", Arrays.asList("continual", "serial")),
    enum_314("律师", "n.", Arrays.asList("lawyer", "attorney", "solicitor", "barrister")),
    enum_315("大声说", "v.", Arrays.asList("exclaim", "shout", "yell")),
    enum_316("引起", "v.", Arrays.asList("cause", "create", "lead", "bring", "incur", "evoke")),
    enum_317("麻烦", "n.", Arrays.asList("trouble", "difficulty", "matter", "problem", "grief")),
    enum_318("协议", "n.", Arrays.asList("agreement", "contract", "treaty", "pact")),
    enum_319("制度", "n.", Arrays.asList("institution", "regime", "bylaw")),
    enum_320("有区别的", "adj.", Arrays.asList("discriminatory", "differentiated")),
    enum_321("保持", "v.", Arrays.asList("hold", "remain", "maintain", "sustain", "keep", "retain")),
    enum_322("管子（管状物）", "n.", Arrays.asList("pipe", "tube")),
    enum_323("设备", "n.", Arrays.asList("device", "equipment", "facility")),
    enum_324("风景", "n.", Arrays.asList("view", "scenery", "landscape", "sight")),
    enum_325("看", "v.", Arrays.asList("see", "sight", "view", "watch", "observe", "gaze", "look", "glimpse")),
    enum_326("楼层", "n.", Arrays.asList("floor", "storey")),
    enum_327("挖", "v.", Arrays.asList("dig", "excavate")),
    enum_328("广场", "n.", Arrays.asList("square", "concourse", "plaza")),
    enum_329("环境", "n.", Arrays.asList("environment", "condition", "context", "surrounding")),
    enum_330("预制的", "adj.", Arrays.asList("preassemble", "prefabricated")),
    enum_331("大厅", "n.", Arrays.asList("lobby", "hall")),
    enum_332("快速的", "adj.", Arrays.asList("fast", "express", "quick", "rapid", "swift", "prompt")),
    enum_333("租", "v.", Arrays.asList("hire", "rent", "lease")),
    enum_334("排", "n.", Arrays.asList("row", "line", "bank", "rank")),
    enum_335("开始的", "adj.", Arrays.asList("initial", "preliminary")),
    enum_336("买", "v.", Arrays.asList("buy", "bought", "purchase")),
    enum_337("卖", "v.", Arrays.asList("sell", "sold", "vend")),
    enum_338("软的", "adj.", Arrays.asList("soft", "tender", "velvet")),
    enum_339("提交", "v.", Arrays.asList("present", "submit", "tender", "put in", "refer")),
    enum_340("开创性的", "adj.", Arrays.asList("groundbreaking", "pioneer")),
    enum_341("建筑物", "n.", Arrays.asList("building", "complex", "structure", "construction", "institution")),
    enum_342("游客", "n.", Arrays.asList("traveller", "tourist", "farer", "")),
    enum_343("伤害", "v.", Arrays.asList("injure", "hurt", "harm", "damage", "bruise", "scar")),
    enum_344("攻击", "v.", Arrays.asList("attack", "assault")),
    enum_345("遭受", "v.", Arrays.asList("suffer", "inflict")),
    enum_346("残忍的", "v.", Arrays.asList("cruel", "vicious", "savage")),
    enum_347("飞机", "n.", Arrays.asList("plane",  "airplane", "aeroplane", "aircraft", "airliner", "flight", "jet")),
    enum_348("只不过", "adv.", Arrays.asList("only", "merely", "just", "barely")),
    enum_349("撞", "v.", Arrays.asList("crash", "collide", "hit", "smash", "bump")),
    enum_350("重要的", "adj.", Arrays.asList("important", "crucial", "essential", "critical")),
    enum_351("扔", "v.", Arrays.asList("throw", "hurl", "cast", "pitch")),
    enum_352("帮助", "n.", Arrays.asList("assistance", "aim")),
    enum_353("愤怒", "v.", Arrays.asList("anger", "rage")),
    enum_354("交换", "v.", Arrays.asList("change", "commute")),
    enum_355("受害者", "n.", Arrays.asList("victim", "casualty")),
    enum_356("倒塌", "v.", Arrays.asList("collapse", "molder")),
    enum_357("相邻的", "adj.", Arrays.asList("adjoining", "adjacent", "nearby", "neighbouring")),
    enum_358("使困惑", "v.", Arrays.asList("puzzle", "bewilder", "confuse")),
    enum_359("猜想", "v.", Arrays.asList("guess", "suppose", "assume", "presume", "speculate", "expect", "reckon", "visualize")),
    enum_360("许多", "n.", Arrays.asList("a number of", "a")),
    enum_361("场景", "n.", Arrays.asList("sight", "spectacle", "scene")),
    enum_362("勇气", "n.", Arrays.asList("courage", "fortitude")),
    enum_363("遗体", "n.", Arrays.asList("remains", "corpse", "dead body")),
    enum_364("残骸", "n.", Arrays.asList("wreck", "ruin", "remain", "wreckage", "rubble", "debris")),
    enum_365("遗产（遗留之物）", "n.", Arrays.asList("heritage", "legacy", "inheritance", "")),
    enum_366("不重要的", "adj.", Arrays.asList("unimportant", "trivial")),
    enum_367("死亡", "n.", Arrays.asList("death", "fatality", "casualty")),
    enum_368("随意的", "adj.", Arrays.asList("informal", "casual")),
    enum_369("燃烧", "v.", Arrays.asList("burn", "smolder","ignite", "blaze", "flame", "inflame", "flare (up)", "")),
    enum_370("易碎的", "adj.", Arrays.asList("delicate", "vulnerable","fragile","brittle")),
    enum_371("表转折", "conj.", Arrays.asList("but", "however","nevertheless","although","though","still")),
    enum_372("做", "v.", Arrays.asList("make", "act","perpetrate（不好的事）")),
    enum_373("表否定", "adv.", Arrays.asList("not", "no more", "no longer")),
    enum_374("改正", "v.", Arrays.asList("correct", "revise")),
    enum_375("表递进", "adv.", Arrays.asList("a", "a")),
    enum_376("偏见", "v.", Arrays.asList("discriminate", "bias", "prejudice")),
    enum_377("保证", "v.", Arrays.asList("assure", "ensure","")),
    enum_378("a", "v.", Arrays.asList("a", "a")),
    enum_379("a", "v.", Arrays.asList("a", "a")),
    enum_380("a", "v.", Arrays.asList("a", "a")),
    enum_381("a", "v.", Arrays.asList("a", "a")),
    enum_382("a", "v.", Arrays.asList("a", "a")),
    enum_383("a", "v.", Arrays.asList("a", "a")),
    enum_384("a", "v.", Arrays.asList("a", "a")),
    enum_385("a", "v.", Arrays.asList("a", "a")),
    enum_386("a", "v.", Arrays.asList("a", "a")),
    enum_387("a", "v.", Arrays.asList("a", "a")),
    enum_388("a", "v.", Arrays.asList("a", "a")),
    enum_389("a", "v.", Arrays.asList("a", "a")),
    enum_390("a", "v.", Arrays.asList("a", "a")),
    enum_391("a", "v.", Arrays.asList("a", "a")),
    enum_392("a", "v.", Arrays.asList("a", "a")),
    enum_393("a", "v.", Arrays.asList("a", "a")),
    enum_394("a", "v.", Arrays.asList("a", "a")),
    enum_395("a", "v.", Arrays.asList("a", "a")),
    enum_396("a", "v.", Arrays.asList("a", "a")),
    enum_397("a", "v.", Arrays.asList("a", "a")),
    enum_398("a", "v.", Arrays.asList("a", "a")),
    enum_399("a", "v.", Arrays.asList("a", "a")),
    enum_400("a", "v.", Arrays.asList("a", "a")),
    enum_401("a", "v.", Arrays.asList("a", "a")),
    enum_402("a", "v.", Arrays.asList("a", "a")),
    enum_403("a", "v.", Arrays.asList("a", "a")),
    enum_404("a", "v.", Arrays.asList("a", "a")),
    enum_405("a", "v.", Arrays.asList("a", "a")),
    enum_406("a", "v.", Arrays.asList("a", "a")),
    enum_407("a", "v.", Arrays.asList("a", "a")),
    enum_408("a", "v.", Arrays.asList("a", "a")),
    enum_409("a", "v.", Arrays.asList("a", "a")),
    enum_410("a", "v.", Arrays.asList("a", "a")),
    enum_411("a", "v.", Arrays.asList("a", "a")),
    enum_412("a", "v.", Arrays.asList("a", "a")),
    enum_413("a", "v.", Arrays.asList("a", "a")),
    enum_414("a", "v.", Arrays.asList("a", "a")),
    enum_415("a", "v.", Arrays.asList("a", "a")),
    enum_416("a", "v.", Arrays.asList("a", "a")),
    enum_417("a", "v.", Arrays.asList("a", "a")),
    enum_418("a", "v.", Arrays.asList("a", "a")),
    enum_419("a", "v.", Arrays.asList("a", "a")),
    enum_420("a", "v.", Arrays.asList("a", "a")),
    enum_421("a", "v.", Arrays.asList("a", "a")),
    enum_422("a", "v.", Arrays.asList("a", "a")),
    enum_423("a", "v.", Arrays.asList("a", "a")),
    enum_424("a", "v.", Arrays.asList("a", "a")),
    enum_425("a", "v.", Arrays.asList("a", "a")),
    enum_426("a", "v.", Arrays.asList("a", "a")),
    enum_427("a", "v.", Arrays.asList("a", "a")),
    enum_428("a", "v.", Arrays.asList("a", "a")),
    enum_429("a", "v.", Arrays.asList("a", "a")),
    enum_430("a", "v.", Arrays.asList("a", "a")),
    enum_431("a", "v.", Arrays.asList("a", "a")),
    enum_432("a", "v.", Arrays.asList("a", "a")),
    enum_433("a", "v.", Arrays.asList("a", "a")),
    enum_434("a", "v.", Arrays.asList("a", "a")),
    enum_435("a", "v.", Arrays.asList("a", "a")),
    enum_436("a", "v.", Arrays.asList("a", "a")),
    enum_437("a", "v.", Arrays.asList("a", "a")),
    enum_438("a", "v.", Arrays.asList("a", "a")),
    enum_439("a", "v.", Arrays.asList("a", "a")),
    enum_440("a", "v.", Arrays.asList("a", "a")),
    enum_441("a", "v.", Arrays.asList("a", "a")),
    enum_442("a", "v.", Arrays.asList("a", "a")),
    enum_443("a", "v.", Arrays.asList("a", "a")),
    enum_444("a", "v.", Arrays.asList("a", "a")),
    enum_445("a", "v.", Arrays.asList("a", "a")),
    enum_446("a", "v.", Arrays.asList("a", "a")),
    enum_447("a", "v.", Arrays.asList("a", "a")),
    enum_448("a", "v.", Arrays.asList("a", "a")),
    enum_449("a", "v.", Arrays.asList("a", "a")),
    enum_450("a", "v.", Arrays.asList("a", "a")),
    enum_451("a", "v.", Arrays.asList("a", "a")),
    enum_452("a", "v.", Arrays.asList("a", "a")),
    enum_453("a", "v.", Arrays.asList("a", "a")),
    enum_454("a", "v.", Arrays.asList("a", "a")),
    enum_455("a", "v.", Arrays.asList("a", "a")),
    enum_456("a", "v.", Arrays.asList("a", "a")),
    enum_457("a", "v.", Arrays.asList("a", "a")),
    enum_458("a", "v.", Arrays.asList("a", "a")),
    enum_459("a", "v.", Arrays.asList("a", "a")),
    enum_460("a", "v.", Arrays.asList("a", "a")),
    enum_461("a", "v.", Arrays.asList("a", "a")),
    enum_462("a", "v.", Arrays.asList("a", "a")),
    enum_463("a", "v.", Arrays.asList("a", "a")),
    enum_464("a", "v.", Arrays.asList("a", "a")),
    enum_465("a", "v.", Arrays.asList("a", "a")),
    enum_466("a", "v.", Arrays.asList("a", "a")),
    enum_467("a", "v.", Arrays.asList("a", "a")),
    enum_468("a", "v.", Arrays.asList("a", "a")),
    enum_469("a", "v.", Arrays.asList("a", "a")),
    enum_470("a", "v.", Arrays.asList("a", "a")),
    enum_471("a", "v.", Arrays.asList("a", "a")),
    enum_472("a", "v.", Arrays.asList("a", "a")),
    enum_473("a", "v.", Arrays.asList("a", "a")),
    enum_474("a", "v.", Arrays.asList("a", "a")),
    enum_475("a", "v.", Arrays.asList("a", "a")),
    enum_476("a", "v.", Arrays.asList("a", "a")),
    enum_477("a", "v.", Arrays.asList("a", "a")),
    enum_478("a", "v.", Arrays.asList("a", "a")),
    enum_479("a", "v.", Arrays.asList("a", "a")),
    enum_480("a", "v.", Arrays.asList("a", "a")),
    enum_481("a", "v.", Arrays.asList("a", "a")),
    enum_482("a", "v.", Arrays.asList("a", "a")),
    enum_483("a", "v.", Arrays.asList("a", "a")),
    enum_484("a", "v.", Arrays.asList("a", "a")),
    enum_485("a", "v.", Arrays.asList("a", "a")),
    enum_486("a", "v.", Arrays.asList("a", "a")),
    enum_487("a", "v.", Arrays.asList("a", "a")),
    enum_488("a", "v.", Arrays.asList("a", "a")),
    enum_489("a", "v.", Arrays.asList("a", "a")),
    enum_490("a", "v.", Arrays.asList("a", "a")),
    enum_491("a", "v.", Arrays.asList("a", "a")),
    enum_492("a", "v.", Arrays.asList("a", "a")),
    enum_493("a", "v.", Arrays.asList("a", "a")),
    enum_494("a", "v.", Arrays.asList("a", "a")),
    enum_495("a", "v.", Arrays.asList("a", "a")),
    enum_496("a", "v.", Arrays.asList("a", "a")),
    enum_497("a", "v.", Arrays.asList("a", "a")),
    enum_498("a", "v.", Arrays.asList("a", "a")),
    enum_499("a", "v.", Arrays.asList("a", "a")),
    enum_500("a", "v.", Arrays.asList("a", "a")),
    enum_501("a", "v.", Arrays.asList("a", "a")),
    enum_502("a", "v.", Arrays.asList("a", "a")),
    enum_503("a", "v.", Arrays.asList("a", "a")),
    enum_504("a", "v.", Arrays.asList("a", "a")),
    enum_505("a", "v.", Arrays.asList("a", "a")),
    enum_506("a", "v.", Arrays.asList("a", "a")),
    enum_507("a", "v.", Arrays.asList("a", "a")),
    enum_508("a", "v.", Arrays.asList("a", "a")),
    enum_509("a", "v.", Arrays.asList("a", "a")),
    enum_510("a", "v.", Arrays.asList("a", "a")),
    enum_511("a", "v.", Arrays.asList("a", "a")),
    enum_512("a", "v.", Arrays.asList("a", "a")),
    enum_513("a", "v.", Arrays.asList("a", "a")),
    enum_514("a", "v.", Arrays.asList("a", "a")),
    enum_515("a", "v.", Arrays.asList("a", "a")),
    enum_516("a", "v.", Arrays.asList("a", "a")),
    enum_517("a", "v.", Arrays.asList("a", "a")),
    enum_518("a", "v.", Arrays.asList("a", "a")),
    enum_519("a", "v.", Arrays.asList("a", "a")),
    enum_520("a", "v.", Arrays.asList("a", "a")),
    enum_521("a", "v.", Arrays.asList("a", "a")),
    enum_522("a", "v.", Arrays.asList("a", "a")),
    enum_523("a", "v.", Arrays.asList("a", "a")),
    enum_524("a", "v.", Arrays.asList("a", "a")),
    enum_525("a", "v.", Arrays.asList("a", "a")),
    enum_526("a", "v.", Arrays.asList("a", "a")),
    enum_527("a", "v.", Arrays.asList("a", "a")),
    enum_528("a", "v.", Arrays.asList("a", "a")),
    enum_529("a", "v.", Arrays.asList("a", "a")),
    enum_530("a", "v.", Arrays.asList("a", "a")),
    enum_531("a", "v.", Arrays.asList("a", "a")),
    enum_532("a", "v.", Arrays.asList("a", "a")),
    enum_533("a", "v.", Arrays.asList("a", "a")),
    enum_534("a", "v.", Arrays.asList("a", "a")),
    enum_535("a", "v.", Arrays.asList("a", "a")),
    enum_536("a", "v.", Arrays.asList("a", "a")),
    enum_537("a", "v.", Arrays.asList("a", "a")),
    enum_538("a", "v.", Arrays.asList("a", "a")),
    enum_539("a", "v.", Arrays.asList("a", "a")),
    enum_540("a", "v.", Arrays.asList("a", "a")),
    enum_541("a", "v.", Arrays.asList("a", "a")),
    enum_542("a", "v.", Arrays.asList("a", "a")),
    enum_543("a", "v.", Arrays.asList("a", "a")),
    enum_544("a", "v.", Arrays.asList("a", "a")),
    enum_545("a", "v.", Arrays.asList("a", "a")),
    enum_546("a", "v.", Arrays.asList("a", "a")),
    enum_547("a", "v.", Arrays.asList("a", "a")),
    enum_548("a", "v.", Arrays.asList("a", "a")),
    enum_549("a", "v.", Arrays.asList("a", "a")),
    enum_550("a", "v.", Arrays.asList("a", "a")),
    enum_551("a", "v.", Arrays.asList("a", "a")),













    ;

    String chinese;
    String pos;
    List<String> engList;

    Synonym(String chinese, String pos, List<String> engList) {
        this.chinese = chinese;
        this.pos = pos;
        this.engList = engList;
    }


}
