package com.test;

import cn.hutool.core.collection.CollUtil;
import cn.hutool.core.util.StrUtil;
import cn.hutool.json.JSONObjectIter;
import cn.hutool.system.SystemUtil;
import com.alibaba.fastjson.JSONObject;
import com.book.FifteenArticle;
import com.neclesson.ThirdVolume;
import com.other.Welcome10;
import com.words.*;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;

import java.io.*;
import java.lang.reflect.Method;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.nio.channels.Channel;
import java.nio.channels.FileChannel;
import java.nio.channels.FileLock;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.*;
import java.util.stream.Collectors;

import static com.words.TestFour1.*;
import static com.words.TestFour3.*;
import static com.words.TestFour4.*;
import static com.words.TestFour11.*;
import static com.words.TestFour8.*;
import static com.words.TestFour9.*;
import static com.words.TestFour5.*;
import static com.words.TestFour2.*;
import static com.words.TestFour6.*;
import static com.words.TestIelts.*;
import static com.words.TestToefl.*;
import static com.words.TestFour7.*;
import static com.words.TestFour10.*;

@Slf4j
public class TestMain2 {


    private TestCz testCz = new TestCz();
    private TestGz testGz = new TestGz();
    private TestIelts testIelts = new TestIelts();
    private TestToefl testToefl = new TestToefl();




    static final List<String> keywords = Arrays.asList("abstract", "assert", "boolean",

            "break", "byte", "case", "catch", "char", "class", "const",

            "continue", "default", "do", "double", "else", "extends", "false",

            "final", "finally", "float", "for", "goto", "if", "implements",

            "import", "instanceof", "int", "interface", "long", "native",

            "new", "null", "package", "private", "protected", "public",

            "return", "short", "static", "strictfp", "super", "switch",

            "synchronized", "this", "throw", "throws", "transient", "true",

            "try", "void", "volatile", "while" );


    @Test
    public void showMethods() throws NoSuchMethodException, SocketException, UnknownHostException {

        Class<TestToefl> TestFourClass = TestToefl.class;
        List<Method> methodList = Arrays.asList(TestFourClass.getMethods());

        methodList.stream().forEach(e -> {

            if(e.getDeclaringClass().getName().equals("com.demo.text.TestToefl")){
                log.info("TestToefl." + e.getName() + "();");
            }
        });

        String address = SystemUtil.getHostInfo().getAddress();
        System.out.println(address);

        Enumeration<NetworkInterface> networkInterfaces = NetworkInterface.getNetworkInterfaces();
        networkInterfaces.asIterator().forEachRemaining(networkInterface -> {
            Enumeration<InetAddress> inetAddresses = networkInterface.getInetAddresses();
            while(inetAddresses.hasMoreElements()) {
                InetAddress inetAddr = (InetAddress)inetAddresses.nextElement();
                if (!inetAddr.isLoopbackAddress() && !inetAddr.isLinkLocalAddress() && !inetAddr.isMulticastAddress()) {
                    System.out.println(networkInterface.getName() + ":" + inetAddr.getHostAddress() + ":" + getMacByInetAddress(networkInterface.getInetAddresses().nextElement()));
                }
            }
        });

    }

    protected static String getMacByInetAddress(InetAddress inetAddr) {
        try {
            byte[] mac = NetworkInterface.getByInetAddress(inetAddr).getHardwareAddress();
            StringBuffer stringBuffer = new StringBuffer();

            for(int i = 0; i < mac.length; ++i) {
                if (i != 0) {
                    stringBuffer.append("-");
                }

                String temp = Integer.toHexString(mac[i] & 255);
                if (temp.length() == 1) {
                    stringBuffer.append("0" + temp);
                } else {
                    stringBuffer.append(temp);
                }
            }

            return stringBuffer.toString().toUpperCase();
        } catch (SocketException var6) {
            return null;
        }
    }



    @SneakyThrows
    @Test
    public void generationMethods() {

        Class<TestFour1> testFour1Class = TestFour1.class;
        Method[] methods = testFour1Class.getMethods();
        Set<String> collect = Arrays.stream(methods).map(e -> e.getName()).collect(Collectors.toSet());

        Class<TestGz> testFourClass2 = TestGz.class;
        Method[] method2 = testFourClass2.getMethods();
        Set<String> collect2 = Arrays.stream(method2).map(e -> e.getName()).collect(Collectors.toSet());

        Class<TestCz> testFourClass3 = TestCz.class;
        Method[] method3 = testFourClass3.getMethods();
        Set<String> collect3 = Arrays.stream(method3).map(e -> e.getName()).collect(Collectors.toSet());

        Class<TestIelts> testFourClass4 = TestIelts.class;
        Method[] method4 = testFourClass4.getMethods();
        Set<String> collect4 = Arrays.stream(method4).map(e -> e.getName()).collect(Collectors.toSet());

        File file = new File("E:\\个人资料\\我的阅读\\dict-master\\book\\1521164640451_TOEFL_2\\TOEFL_2.json");
        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_8));
        String temp = null;
        List<Welcome10> all = new ArrayList<>();
        while ((temp = bufferedReader.readLine()) != null){
            all.add(JSONObject.parseObject(temp, Welcome10.class));
        }

        all.parallelStream().forEach(welcome10 -> {

            synchronized (TestMain2.class){
                String headWord = welcome10.getHeadWord();
                Welcome10.Welcome10Content content = welcome10.getContent();
                Welcome10.ContentWord word = content.getWord();
                Welcome10.WordContent content1 = word.getContent();

                headWord = headWord.replaceAll(" ", "_").replaceAll("-", "_");

                if(collect.contains(headWord) || collect2.contains(headWord) || collect3.contains(headWord) || collect4.contains(headWord)){
                    return;
                }


                log.info("/**");

                log.info("* @pronounce " + content1.getUkphone());

                for (Welcome10.Tran tran : content1.getTrans()) {
                    log.info("* @explain " + tran.getPos() + "." + tran.getTranCN());
                }

                if(content1.getSentence() != null && content1.getSentence().getSentences() != null){
                    for (int i = 0; i < content1.getSentence().getSentences().length; i++) {

                        Welcome10.SentenceSentence sentence = content1.getSentence().getSentences()[i];
                        int i_temp = i+1;
                        log.info("* @e.g."+i_temp+" " + sentence.getSContent() + "." + sentence.getSCN());
                    }
                }

                Welcome10.RelWord relWord = content1.getRelWord();
                if(relWord != null){
                    String rwtxt = "";
                    rwtxt += "* @same ";
                    for (int i = 0; i < relWord.getRels().length; i++) {
                        Welcome10.Rel rel = relWord.getRels()[i];
                        rwtxt += rel.getPos() + ". " + CollUtil.join(Arrays.asList(rel.getWords()).stream().map(Welcome10.WordElement::getHwd).collect(Collectors.toList()), "、");
                        rwtxt += "，";
                    }

                    if(StrUtil.isNotBlank(rwtxt)){
                        log.info(rwtxt);
                    }
                }

                log.info("*/");
                if(keywords.contains(headWord)){
                    headWord += "_";
                }

                log.info("public static void "+headWord+"(){}");
                log.info("\n");
            }
        });
        log.info("总数量" + all.size());
    }



    @SneakyThrows
    public static void methodListFour2(String[] args) {
        // The company provided Chinese Canadians with merchandise not readily available in Vancouver and exported Canadian foodstuffs to China.
        merchandise();

        List<Integer> integers1 = Arrays.asList(1, 2, 3, 4);
        integers1.subList(0, 3);
        List<Integer> integers2 = Arrays.asList(3, 4, 5, 6);

        Collection<Integer> subtract1 = CollUtil.subtract(integers1, integers2);
        System.out.println(subtract1);

        Collection<Integer> subtract2 = CollUtil.subtract(integers2, integers1);
        System.out.println(subtract2);

        TestFour4.ribbon();
        TestFour5.scholar();
        TestFour5.scissors();
        TestFour4.rotten();
        TestFour5.score();
        TestFour4.route();
        TestFour4.roller();
        TestFour4.revolt();
        TestFour5.practice();
        TestFour5.praise();
        TestFour5.precaution();
        TestFour5.preceding();
        TestFour4.sail();
        TestFour5.pray();
        TestFour5.scenery();
        TestFour5.precise();
        TestFour5.predict();
        TestFour4.rotary();
        TestFour5.preface();
        TestFour4.reward();
        TestFour4.routine();
        TestFour4.saddle();
        TestFour5.scientific();
        TestFour4.ripe();
        TestFour4.rhythm();
        TestFour4.satellite();
        TestFour4.ridiculous();
        TestFour4.rural();
        TestFour4.rouse();
        TestFour5.saw();
        TestFour5.practise();
        TestFour4.rigid();
        TestFour4.sample();
        TestFour5.precious();
        TestFour4.risk();
        TestFour4.revise();
        TestFour4.rib();
        TestFour4.robot();
        TestFour4.ridge();
        TestFour4.revolution();
        TestFour4.romantic();
        TestFour4.rough();
        TestFour4.row();
        TestFour4.roast();
        TestFour4.rotation();
        TestFour4.rid();
        TestFour4.rival();
        TestFour4.rocket();
        TestFour4.royal();
        TestFour4.roar();
        TestFour4.rug();
        TestFour4.rush();
        TestFour4.rust();
        TestFour4.sacrifice();
        TestFour5.scarcely();
        TestFour4.rod();
        TestFour5.sausage();
        TestFour4.Roman();
        TestFour4.sack();
        TestFour4.rifle();
        TestFour5.say();
        TestFour4.sake();
        TestFour5.scatter();
        TestFour5.saucer();
        TestFour11.thoughtful();
        TestFour4.trap();
        TestFour4.tray();
        TestFour11.tolerate();
        TestFour4.treasure();
        TestFour11.torture();
        TestFour11.tissue();
        TestFour4.treatment();
        TestFour4.tremble();
        TestFour4.tremendous();
        TestFour4.trend();
        TestFour4.trial();
        TestFour4.tragedy();
        TestFour4.trick();
        TestFour4.treat();
        TestFour4.triumph();
        TestFour4.troop();
        TestFour11.toilet();
        TestFour4.tropical();
        TestFour4.trumpet();
        TestFour11.touch();
        TestFour4.traffic();
        TestFour4.treaty();
        TestFour11.thrust();
        TestFour11.thickness();
        TestFour4.triangle();
        TestFour11.thrive();
        TestFour11.towel();
        TestFour11.torch();
        TestFour4.trunk();
        TestFour4.trust();
        TestFour11.throughout();
        TestFour4.transistor();
        TestFour4.truth();
        TestFour11.thunder();
        TestFour11.textile();
        TestFour11.thorough();
        TestFour11.tin();
        TestFour11.threaten();
        TestFour11.thereby();
        TestFour11.toe();
        TestFour11.tone();
        TestFour11.tough();
        TestFour11.tidy();
        TestFour11.tolerance();
        TestFour11.threat();
        TestFour11.terrible();
        TestFour11.thus();
        TestFour11.territory();
        TestFour11.tide();
        TestFour11.tip();
        TestFour11.tour();
        TestFour11.tourist();
        TestFour11.tower();
        TestFour11.track();
        TestFour11.tire();
        TestFour11.therefore();
        TestFour11.toast();
        TestFour11.tractor();
        TestFour11.throat();
        TestFour11.terror();
        TestFour4.trade();
        TestFour4.transmit();
        TestFour4.transport();
        TestFour4.question();
        TestFour4.unless();
        TestFour4.uneasy();
        TestFour4.typewriter();
        TestFour4.puzzle();
        TestFour4.quality();
        TestFour4.typical();
        TestFour4.qualify();
        TestFour4.quarrel();
        TestFour4.quiet();
        TestFour4.quit();
        TestFour4.quotation();
        TestFour4.rabbit();
        TestFour4.ultimate();
        TestFour4.race();
        TestFour4.universal();
        TestFour4.racial();
        TestFour4.quarter();
        TestFour4.radar();
        TestFour4.twin();
        TestFour4.unite();
        TestFour4.quick();
        TestFour4.rack();
        TestFour4.radio();
        TestFour4.rag();
        TestFour4.quite();
        TestFour4.rail();
        TestFour4.radiation();
        TestFour4.railway();
        TestFour4.uncover();
        TestFour4.rain();
        TestFour4.rainbow();
        TestFour4.rainy();
        TestFour4.railroad();
        TestFour4.underneath();
        TestFour4.rat();
        TestFour4.rate();
        TestFour4.tune();
        TestFour4.uniform();
        TestFour4.twist();
        TestFour4.undertake();
        TestFour4.rapid();
        TestFour4.rank();
        TestFour4.rational();
        TestFour4.undo();
        TestFour4.unique();
        TestFour4.tunnel();
        TestFour4.tyre();
        TestFour4.unity();
        TestFour4.undergo();
        TestFour4.queen();
        TestFour4.rarely();
        TestFour4.tube();
        TestFour4.rare();
        TestFour4.turbine();
        TestFour4.rather();
        TestFour4.ratio();
        TestFour4.ray();
        TestFour4.reach();
        TestFour4.react();
        TestFour4.quantity();
        TestFour4.radius();
        TestFour4.underline();
        TestFour4.typist();
        TestFour4.reflection();
        TestFour4.reflect();
        TestFour4.relativity();
        TestFour4.recently();
        TestFour4.refusal();
        TestFour4.refuse();
        TestFour4.relieve();
        TestFour4.religion();
        TestFour4.eighty();
        TestFour4.elbow();
        TestFour4.reality();
        TestFour4.regular();
        TestFour4.reject();
        TestFour4.receipt();
        TestFour4.recommend();
        TestFour4.realize();
        TestFour4.reasonable();
        TestFour4.refer();
        TestFour4.rebel();
        TestFour4.refine();
        TestFour4.relate();
        TestFour4.regulate();
        TestFour4.regret();
        TestFour4.relax();
        TestFour4.relevant();
        TestFour4.reliable();
        TestFour4.either();
        TestFour4.elect();
        TestFour4.election();
        TestFour4.electrical();
        TestFour4.reaction();
        TestFour4.regulation();
        TestFour4.elaborate();
        TestFour4.reduction();
        TestFour4.regardless();
        TestFour4.reception();
        TestFour4.religious();
        TestFour4.elastic();
        TestFour4.elder();
        TestFour4.reform();
        TestFour4.electric();
        TestFour4.electron();
        TestFour4.really();
        TestFour4.reflexion();
        TestFour4.real();
        TestFour4.realm();
        TestFour4.recognize();
        TestFour4.regard();
        TestFour4.regarding();
        TestFour4.reinforce();
        TestFour4.relation();
        TestFour4.reluctant();
        TestFour4.rely();
        TestFour4.refresh();
        TestFour4.electronic();
        TestFour4.elementary();
        TestFour4.receive();
        TestFour4.recent();
        TestFour4.recall();
        TestFour4.relief();
        TestFour4.rear();
        TestFour4.recorder();
        TestFour4.recover();
        TestFour4.recovery();
        TestFour4.engine();
        TestFour4.repetition();
        TestFour4.represent();
        TestFour4.reserve();
        TestFour4.reservior();
        TestFour4.enough();
        TestFour4.elephant();
        TestFour4.reputation();
        TestFour4.residence();
        TestFour4.remedy();
        TestFour4.render();
        TestFour4.else_();
        TestFour4.emergency();
        TestFour4.empire();
        TestFour4.emerge();
        TestFour4.employ();
        TestFour4.embarrass();
        TestFour4.employee();
        TestFour4.eliminate();
        TestFour4.emphasize();
        TestFour4.employer();
        TestFour4.emotion();
        TestFour4.encounter();
        TestFour4.eleven();
        TestFour4.emperor();
        TestFour4.endure();
        TestFour4.energy();
        TestFour4.emit();
        TestFour4.remark();
        TestFour4.remarkable();
        TestFour4.employment();
        TestFour4.encourage();
        TestFour4.ending();
        TestFour4.enemy();
        TestFour4.enjoy();
        TestFour4.remember();
        TestFour4.endless();
        TestFour4.enforce();
        TestFour4.remind();
        TestFour4.elevator();
        TestFour4.emotional();
        TestFour4.engage();
        TestFour4.engineer();
        TestFour4.removal();
        TestFour4.renew();
        TestFour4.eleventh();
        TestFour4.rent();
        TestFour4.repeatedly();
        TestFour4.reply();
        TestFour4.reporter();
        TestFour4.emphasis();
        TestFour4.enclose();
        TestFour4.repair();
        TestFour4.English();
        TestFour4.Englishman();
        TestFour4.reproduce();
        TestFour4.elsewhere();
        TestFour4.republic();
        TestFour4.rescue();
        TestFour4.embrace();
        TestFour4.England();
        TestFour4.require();
        TestFour4.resemble();
        TestFour4.enormous();
        TestFour4.reveal();
        TestFour4.resist();
        TestFour4.response();
        TestFour4.resident();
        TestFour4.restless();
        TestFour4.resistant();
        TestFour4.retain();
        TestFour4.review();
        TestFour4.resign();
        TestFour4.resistance();
        TestFour4.respective();
        TestFour4.respond();
        TestFour4.restraint();
        TestFour4.resort();
        TestFour4.restrict();
        TestFour4.retire();
        TestFour4.restrain();
        TestFour4.restore();
        TestFour4.retreat();
        TestFour4.request();
        TestFour11.describe();
        TestFour8.assign();
        TestFour4.remain();
        TestFour8.comparison();
        TestFour7.expert();
        TestFour6.formal();
        TestFour10.include();
        TestFour6.mess();
        TestFour9.additional();
        TestFour7.different();
        TestFour3.visual();
        TestFour9.bean();
        TestFour7.January();
        TestFour10.February();
        TestFour3.March();
        TestFour9.April();
        TestFour7.June();
        TestFour7.July();
        TestFour8.August();
        TestFour8.October();
        TestFour8.November();
        TestFour11.December();
        TestFour10.Monday();
        TestFour6.Friday();
        TestFour11.water();
        TestFour11.widow();
        TestFour11.wing();
        TestFour11.tension();
        TestFour11.worthy();
        TestFour11.weed();
        TestFour11.wooden();
        TestFour11.youth();
        TestFour11.terminal();
        TestFour11.welfare();
        TestFour11.whip();
        TestFour3.vivid();
        TestFour3.volcano();
        TestFour11.wheat();
        TestFour11.whistle();
        TestFour11.wicked();
        TestFour11.withdraw();
        TestFour11.weld();
        TestFour11.weep();
        TestFour11.whisper();
        TestFour11.waggon();
        TestFour11.volume();
        TestFour11.willing();
        TestFour11.withstand();
        TestFour11.worth();
        TestFour11.wave();
        TestFour11.wander();
        TestFour11.worthless();
        TestFour11.wreck();
        TestFour11.worthwhile();
        TestFour11.volt();
        TestFour11.voluntary();
        TestFour11.voyage();
        TestFour11.waken();
        TestFour11.wear();
        TestFour11.wheel();
        TestFour11.wage();
        TestFour11.want();
        TestFour11.whilst();
        TestFour11.waterproof();
        TestFour11.warmth();
        TestFour11.workshop();
        TestFour11.worship();
        TestFour11.worst();
        TestFour11.wind();
        TestFour11.workman();
        TestFour11.wound();
        TestFour11.wrist();
        TestFour11.yard();
        TestFour11.yawn();
        TestFour11.yearly();
        TestFour11.voltage();
        TestFour11.wholly();
        TestFour11.weaken();
        TestFour11.weakness();
        TestFour11.tend();
        TestFour11.tendency();
        TestFour11.wire();
        TestFour11.tender();
        TestFour11.wool();
        TestFour11.wax();
        TestFour11.worm();
        TestFour11.tense();
        TestFour11.weave();
        TestFour2.gown();
        TestFour3.niece();
        TestFour3.nine();
        TestFour3.noble();
        TestFour3.night();
        TestFour3.noisy();
        TestFour3.nonsense();
        TestFour3.noon();
        TestFour3.grain();
        TestFour3.grasp();
        TestFour2.neutral();
        TestFour3.grass();
        TestFour2.goods();
        TestFour2.newly();
        TestFour2.nephew();
        TestFour3.gracious();
        TestFour3.grape();
        TestFour3.grateful();
        TestFour3.gratitude();
        TestFour3.nobody();
        TestFour2.goodness();
        TestFour2.nervous();
        TestFour2.nice();
        TestFour2.government();
        TestFour3.grandson();
        TestFour3.grave();
        TestFour3.gravity();
        TestFour3.gray();
        TestFour3.greatly();
        TestFour2.Negro();
        TestFour3.grade();
        TestFour3.gradual();
        TestFour2.govern();
        TestFour3.graduate();
        TestFour2.nest();
        TestFour2.good();
        TestFour3.grammar();
        TestFour3.ninth();
        TestFour3.grand();
        TestFour2.network();
        TestFour2.neither();
        TestFour3.noise();
        TestFour2.never();
        TestFour3.greedy();
        TestFour2.nerve();
        TestFour3.gramme();
        TestFour3.nitrogen();
        TestFour3.graceful();
        TestFour3.grant();
        TestFour3.gradually();
        TestFour3.great();
        TestFour3.Greek();
        TestFour3.ninety();
        TestFour3.green();
        TestFour2.news();
        TestFour3.nineteen();
        TestFour2.grace();
        TestFour2.neighbour();
        TestFour2.golf();
        TestFour2.governor();
        TestFour2.newspaper();
        TestFour2.goose();
        TestFour2.new_();
        TestFour2.golden();
        TestFour3.guilty();
        TestFour3.grip();
        TestFour3.guide();
        TestFour3.grieve();
        TestFour3.gymnasium();
        TestFour3.habit();
        TestFour3.greeting();
        TestFour3.manly();
        TestFour3.marine();
        TestFour3.Marxism();
        TestFour3.maid();
        TestFour3.greet();
        TestFour3.grey();
        TestFour3.guidance();
        TestFour3.grocer();
        TestFour3.hamburger();
        TestFour3.guest();
        TestFour3.mail();
        TestFour3.majority();
        TestFour3.manage();
        TestFour3.many();
        TestFour3.magnet();
        TestFour3.grind();
        TestFour3.hall();
        TestFour3.marriage();
        TestFour3.greenhouse();
        TestFour3.married();
        TestFour3.groan();
        TestFour3.marvellous();
        TestFour3.grocery();
        TestFour3.magnetic();
        TestFour3.marble();
        TestFour3.Marxist();
        TestFour3.guess();
        TestFour3.haircut();
        TestFour3.manner();
        TestFour3.margin();
        TestFour3.market();
        TestFour3.marry();
        TestFour3.gum();
        TestFour3.master();
        TestFour3.mat();
        TestFour3.gulf();
        TestFour3.mainland();
        TestFour3.mainly();
        TestFour3.manual();
        TestFour3.habitual();
        TestFour3.gunpowder();
        TestFour3.hair();
        TestFour3.mass();
        TestFour3.brighten();
        TestFour3.brilliant();
        TestFour3.brim();
        TestFour3.gun();
        TestFour3.bring();
        TestFour3.brisk();
        TestFour3.management();
        TestFour3.mankind();
        TestFour3.male();
        TestFour3.bristle();
        TestFour3.gross();
        TestFour3.maintain();
        TestFour3.ground();
        TestFour3.guarantee();
        TestFour3.burn();
        TestFour3.cake();
        TestFour3.calculator();
        TestFour3.candy();
        TestFour3.cannon();
        TestFour3.butter();
        TestFour3.camp();
        TestFour3.canoe();
        TestFour3.canteen();
        TestFour3.buy();
        TestFour3.cabinet();
        TestFour3.broken();
        TestFour3.bruise();
        TestFour3.brown();
        TestFour3.broad();
        TestFour3.brush();
        TestFour3.British();
        TestFour3.brute();
        TestFour3.brow();
        TestFour3.butterfly();
        TestFour3.bull();
        TestFour3.brood();
        TestFour3.bud();
        TestFour3.button();
        TestFour3.broom();
        TestFour3.bury();
        TestFour3.bunch();
        TestFour3.bronze();
        TestFour3.cable();
        TestFour3.cafe();
        TestFour3.bubble();
        TestFour3.building();
        TestFour3.bulb();
        TestFour3.bullet();
        TestFour3.but();
        TestFour3.cabbage();
        TestFour3.bulk();
        TestFour3.burden();
        TestFour3.cabin();
        TestFour3.brook();
        TestFour3.bureau();
        TestFour3.burst();
        TestFour3.cage();
        TestFour3.calculate();
        TestFour3.camel();
        TestFour3.camera();
        TestFour3.campus();
        TestFour3.can();
        TestFour3.Canadian();
        TestFour3.canal();
        TestFour3.brother();
        TestFour3.bucket();
        TestFour3.cafeteria();
        TestFour3.bush();
        TestFour3.business();
        TestFour3.cancer();
        TestFour3.Britain();
        TestFour3.calm();
        TestFour3.candle();
        TestFour3.brittle();
        TestFour3.bus();
        TestFour3.campaign();
        TestFour3.Canada();
        TestFour3.butcher();
        TestFour3.castle();
        TestFour3.vacant();
        TestFour3.vacuum();
        TestFour3.continuous();
        TestFour3.van();
        TestFour3.captive();
        TestFour3.contempt();
        TestFour3.careful();
        TestFour3.carrot();
        TestFour3.unlikely();
        TestFour3.vague();
        TestFour3.capital();
        TestFour3.care();
        TestFour3.vain();
        TestFour3.career();
        TestFour3.vapour();
        TestFour3.utilize();
        TestFour3.continual();
        TestFour3.vanish();
        TestFour3.case_();
        TestFour3.upright();
        TestFour3.variable();
        TestFour3.variation();
        TestFour3.variety();
        TestFour3.cash();
        TestFour3.various();
        TestFour3.cathedral();
        TestFour3.captain();
        TestFour3.unlike();
        TestFour3.urge();
        TestFour3.vary();
        TestFour3.consistent();
        TestFour3.carbon();
        TestFour3.utmost();
        TestFour3.construct();
        TestFour3.carriage();
        TestFour3.capable();
        TestFour3.cassette();
        TestFour3.catch_();
        TestFour3.cart();
        TestFour3.contact();
        TestFour3.continent();
        TestFour3.car();
        TestFour3.contract();
        TestFour3.continue_();
        TestFour3.casual();
        TestFour3.contain();
        TestFour3.canvas();
        TestFour3.cargo();
        TestFour3.carpenter();
        TestFour3.consult();
        TestFour3.upset();
        TestFour3.upward();
        TestFour3.urban();
        TestFour3.urgent();
        TestFour3.usage();
        TestFour3.carve();
        TestFour3.card();
        TestFour3.careless();
        TestFour3.cattle();
        TestFour3.carpet();
        TestFour3.contest();
        TestFour3.utility();
        TestFour3.utter();
        TestFour3.vision();
        TestFour3.vital();
        TestFour3.vitamin();
        TestFour3.vessel();
        TestFour3.via();
        TestFour3.venture();
        TestFour3.vehicle();
        TestFour3.vice();
        TestFour3.vigorous();
        TestFour3.vinegar();
        TestFour3.violent();
        TestFour3.vast();
        TestFour3.vertical();
        TestFour3.velocity();
        TestFour3.violet();
        TestFour3.virtually();
        TestFour3.veteran();
        TestFour3.vibrate();
        TestFour3.virtue();
        TestFour8.pause();
        TestFour1.stir();
        TestFour1.strap();
        TestFour1.drought();
        TestFour1.sufficient();
        TestFour1.sulphur();
        TestFour1.strange();
        TestFour1.structural();
        TestFour1.supplement();
        TestFour1.suspicious();
        TestFour1.submerge();
        TestFour1.substitute();
        TestFour1.succession();
        TestFour1.subsequent();
        TestFour1.suck();
        TestFour1.survive();
        TestFour1.suspect();
        TestFour1.sweater();
        TestFour1.submarine();
        TestFour1.stuff();
        TestFour1.subway();
        TestFour1.steer();
        TestFour1.suit();
        TestFour1.superior();
        TestFour1.swallow();
        TestFour1.swell();
        TestFour1.stocking();
        TestFour1.stiff();
        TestFour1.strengthen();
        TestFour1.sweep();
        TestFour1.suspicion();
        TestFour1.stem();
        TestFour1.steamer();
        TestFour1.steel();
        TestFour1.stove();
        TestFour1.stroke();
        TestFour1.substance();
        TestFour1.steep();
        TestFour1.stimulate();
        TestFour1.surgery();
        TestFour1.stock();
        TestFour1.sting();
        TestFour1.stranger();
        TestFour1.straw();
        TestFour1.survey();
        TestFour1.sulfur();
        TestFour1.supreme();
        TestFour1.sustain();
        TestFour1.sway();
        TestFour1.swear();
        TestFour1.swift();
        TestFour1.swing();
        TestFour1.sword();
        TestFour1.successive();
        TestFour1.storage();
        TestFour1.storey();
        TestFour1.stretch();
        TestFour1.stripe();
        TestFour1.summarize();
        TestFour1.switch_();
        TestFour1.suppose();
        TestFour1.stoop();
        TestFour1.stress();
        TestFour1.surrender();
        TestFour1.strain();
        TestFour1.centigrade();
        TestFour1.near();
        TestFour1.nearly();
        TestFour1.neat();
        TestFour1.necessity();
        TestFour1.charming();
        TestFour1.champion();
        TestFour1.sympathize();
        TestFour1.tame();
        TestFour1.necklace();
        TestFour1.need();
        TestFour1.needle();
        TestFour1.chemistry();
        TestFour1.needless();
        TestFour1.necessary();
        TestFour1.geography();
        TestFour1.geometry();
        TestFour1.chapter();
        TestFour1.knock();
        TestFour1.cellar();
        TestFour1.chart();
        TestFour1.chemist();
        TestFour1.neck();
        TestFour1.certain();
        TestFour1.cement();
        TestFour1.chess();
        TestFour1.centre();
        TestFour1.cheek();
        TestFour1.charity();
        TestFour1.nearby();
        TestFour1.neglect();
        TestFour1.ceremony();
        TestFour1.cherry();
        TestFour1.knot();
        TestFour1.certainly();
        TestFour1.talk();
        TestFour1.cent();
        TestFour1.chalk();
        TestFour1.central();
        TestFour1.celebrate();
        TestFour1.change();
        TestFour1.charge();
        TestFour1.chase();
        TestFour1.chairman();
        TestFour1.character();
        TestFour1.centimetre();
        TestFour1.challenge();
        TestFour1.tailor();
        TestFour1.tale();
        TestFour1.chair();
        TestFour1.cheap();
        TestFour1.cheat();
        TestFour1.cheer();
        TestFour1.cheerful();
        TestFour1.chemical();
        TestFour1.chamber();
        TestFour1.cell();
        TestFour1.chance();
        TestFour1.cheese();
        TestFour1.century();
        TestFour1.talent();
        TestFour1.cheque();
        TestFour1.knob();
        TestFour1.genuine();
        TestFour1.lamp();
        TestFour1.lap();
        TestFour1.lab();
        TestFour1.lamb();
        TestFour1.lame();
        TestFour1.laugh();
        TestFour1.lately();
        TestFour1.launch();
        TestFour1.lawn();
        TestFour1.landing();
        TestFour1.laundry();
        TestFour1.lag();
        TestFour1.lavatory();
        TestFour1.know();
        TestFour1.law();
        TestFour1.lead();
        TestFour1.laughter();
        TestFour1.latter();
        TestFour1.leader();
        TestFour1.landlady();
        TestFour1.landlord();
        TestFour1.lantern();
        TestFour1.lawyer();
        TestFour1.lack();
        TestFour1.lake();
        TestFour1.late();
        TestFour1.large();
        TestFour1.lay();
        TestFour1.ladder();
        TestFour1.land();
        TestFour1.largely();
        TestFour1.lane();
        TestFour1.lace();
        TestFour1.laser();
        TestFour1.labour();
        TestFour1.lady();
        TestFour1.knowledge();
        TestFour1.later();
        TestFour1.Latin();
        TestFour1.laboratory();
        TestFour2.loyalty();
        TestFour2.lung();
        TestFour2.magazine();
        TestFour2.lover();
        TestFour2.lord();
        TestFour2.giant();
        TestFour2.loyal();
        TestFour2.gift();
        TestFour2.girl();
        TestFour2.give();
        TestFour2.locomotive();
        TestFour2.glance();
        TestFour2.lonely();
        TestFour2.lucky();
        TestFour2.liver();
        TestFour2.ghost();
        TestFour2.glide();
        TestFour2.glare();
        TestFour2.glitter();
        TestFour2.love();
        TestFour2.Germany();
        TestFour2.loaf();
        TestFour2.logic();
        TestFour2.loose();
        TestFour2.glimpse();
        TestFour2.globe();
        TestFour2.gloomy();
        TestFour2.glorious();
        TestFour2.glory();
        TestFour2.lumber();
        TestFour2.luggage();
        TestFour2.lunch();
        TestFour2.madam();
        TestFour2.glove();
        TestFour2.loan();
        TestFour2.luxury();
        TestFour2.glow();
        TestFour2.lot();
        TestFour2.germ();
        TestFour2.locate();
        TestFour2.lovely();
        TestFour2.machine();
        TestFour2.lodge();
        TestFour2.glue();
        TestFour2.living();
        TestFour2.mad();
        TestFour2.loud();
        TestFour2.luck();
        TestFour2.German();
        TestFour2.lump();
        TestFour2.gesture();
        TestFour2.glass();
        TestFour2.loss();
        TestFour2.goal();
        TestFour2.long_();
        TestFour2.lose();
        TestFour2.goat();
        TestFour2.God();
        TestFour2.look();
        TestFour2.loosen();
        TestFour2.glad();
        TestFour2.gold();
        TestFour2.logical();
        TestFour2.lorry();
        TestFour1.less();
        TestFour1.learning();
        TestFour1.childhood();
        TestFour1.learn();
        TestFour1.letter();
        TestFour1.lever();
        TestFour1.leadership();
        TestFour1.leak();
        TestFour1.chest();
        TestFour1.chin();
        TestFour1.license();
        TestFour1.league();
        TestFour1.lean();
        TestFour1.liberation();
        TestFour1.leather();
        TestFour1.lick();
        TestFour1.life();
        TestFour1.light();
        TestFour1.lifetime();
        TestFour1.childish();
        TestFour1.Chinese();
        TestFour1.liberty();
        TestFour1.learned();
        TestFour1.liberate();
        TestFour1.tank();
        TestFour1.leaf();
        TestFour1.taste();
        TestFour1.least();
        TestFour1.legend();
        TestFour1.leave();
        TestFour1.lend();
        TestFour1.lens();
        TestFour1.librarian();
        TestFour1.chill();
        TestFour1.liberal();
        TestFour1.chew();
        TestFour1.chimney();
        TestFour1.China();
        TestFour1.tap();
        TestFour1.technical();
        TestFour1.technician();
        TestFour1.telegram();
        TestFour1.lid();
        TestFour1.chicken();
        TestFour1.library();
        TestFour1.lie();
        TestFour1.leisure();
        TestFour1.let();
        TestFour1.liable();
        TestFour1.lessen();
        TestFour1.liar();
        TestFour1.chief();
        TestFour1.tedious();
        TestFour1.lesson();
        TestFour1.lest();
        TestFour1.telescope();
        TestFour1.lighten();
        TestFour1.lemon();
        TestFour1.lift();
        TestFour1.lightly();
        TestFour1.lecture();
        TestFour1.lieutenant();
        TestFour1.legal();
        TestFour1.leading();
        TestFour2.secretary();
        TestFour2.secure();
        TestFour2.seize();
        TestFour2.senate();
        TestFour2.educate();
        TestFour2.education();
        TestFour1.temple();
        TestFour2.senior();
        TestFour2.sensible();
        TestFour2.sensitive();
        TestFour2.scout();
        TestFour1.drum();
        TestFour1.dull();
        TestFour1.dwelling();
        TestFour1.due();
        TestFour1.dye();
        TestFour1.dry();
        TestFour1.dying();
        TestFour1.drown();
        TestFour1.duty();
        TestFour1.eager();
        TestFour1.durable();
        TestFour1.early();
        TestFour1.tempt();
        TestFour1.dusk();
        TestFour2.earthquake();
        TestFour2.easily();
        TestFour1.dumb();
        TestFour2.eat();
        TestFour2.echo();
        TestFour1.eagle();
        TestFour1.earn();
        TestFour2.earnest();
        TestFour2.ease();
        TestFour2.efficient();
        TestFour2.effort();
        TestFour2.earth();
        TestFour1.drug();
        TestFour2.east();
        TestFour1.temporary();
        TestFour1.during();
        TestFour2.egg();
        TestFour2.eight();
        TestFour2.eighteen();
        TestFour2.eighth();
        TestFour1.temptation();
        TestFour2.eastern();
        TestFour2.edition();
        TestFour2.effect();
        TestFour2.economical();
        TestFour1.dust();
        TestFour1.ear();
        TestFour2.efficiency();
        TestFour2.economy();
        TestFour2.edge();
        TestFour2.scrape();
        TestFour1.drunk();
        TestFour2.easy();
        TestFour2.scratch();
        TestFour1.duck();
        TestFour2.screw();
        TestFour2.seal();
        TestFour2.secondary();
        TestFour2.economic();
        TestFour2.slope();
        TestFour2.sometime();
        TestFour2.somewhat();
        TestFour2.sheet();
        TestFour2.sore();
        TestFour2.soluble();
        TestFour2.shoot();
        TestFour2.sorrow();
        TestFour2.sound();
        TestFour2.somebody();
        TestFour2.shade();
        TestFour2.shave();
        TestFour2.shriek();
        TestFour2.silence();
        TestFour2.simplicity();
        TestFour2.simplify();
        TestFour2.serve();
        TestFour2.simply();
        TestFour2.shed();
        TestFour2.shot();
        TestFour2.similarly();
        TestFour2.silk();
        TestFour2.sincere();
        TestFour2.shortage();
        TestFour2.silver();
        TestFour2.skilled();
        TestFour2.sleeve();
        TestFour2.silent();
        TestFour2.slide();
        TestFour2.soak();
        TestFour2.singular();
        TestFour2.setting();
        TestFour2.shelf();
        TestFour2.skillful();
        TestFour2.settle();
        TestFour2.shear();
        TestFour2.sew();
        TestFour2.shower();
        TestFour2.skim();
        TestFour2.shore();
        TestFour2.silly();
        TestFour2.slam();
        TestFour2.slender();
        TestFour2.slippery();
        TestFour2.slit();
        TestFour2.shortly();
        TestFour2.separate();
        TestFour2.shelter();
        TestFour2.smart();
        TestFour2.shiver();
        TestFour2.similar();
        TestFour2.sketch();
        TestFour2.solemn();
        TestFour2.solar();
        TestFour2.sole();
        TestFour2.solution();
        TestFour2.sideways();
        TestFour2.series();
        TestFour2.solve();
        TestFour2.somehow();
        TestFour2.soil();
        TestFour2.settlement();
        TestFour2.shield();
        TestFour2.solid();
        TestFour2.class_();
        TestFour2.sow();
        TestFour2.closely();
        TestFour2.clothing();
        TestFour2.spray();
        TestFour2.church();
        TestFour2.specific();
        TestFour2.circulate();
        TestFour2.cloak();
        TestFour2.spoil();
        TestFour2.sour();
        TestFour2.sponsor();
        TestFour2.Christian();
        TestFour2.circuit();
        TestFour2.specialist();
        TestFour2.circular();
        TestFour2.cloud();
        TestFour2.clothe();
        TestFour2.choke();
        TestFour2.clap();
        TestFour2.spacecraft();
        TestFour2.specialize();
        TestFour2.club();
        TestFour2.claw();
        TestFour2.clarify();
        TestFour2.clue();
        TestFour2.classify();
        TestFour2.Christmas();
        TestFour2.cloudy();
        TestFour2.sportsman();
        TestFour2.clumsy();
        TestFour2.classroom();
        TestFour2.spite();
        TestFour2.chocolate();
        TestFour2.cinema();
        TestFour2.sphere();
        TestFour2.spin();
        TestFour2.chop();
        TestFour2.civil();
        TestFour2.civilize();
        TestFour2.clasp();
        TestFour2.clay();
        TestFour2.cigaret();
        TestFour2.clever();
        TestFour2.spade();
        TestFour2.specimen();
        TestFour2.classical();
        TestFour2.choose();
        TestFour2.citizen();
        TestFour2.clearly();
        TestFour2.clerk();
        TestFour2.cliff();
        TestFour2.climate();
        TestFour2.cloth();
        TestFour2.clothes();
        TestFour2.climb();
        TestFour2.claim();
        TestFour2.spark();
        TestFour2.circle();
        TestFour2.specify();
        TestFour2.city();
        TestFour2.spill();
        TestFour2.classmate();
        TestFour2.span();
        TestFour2.lip();
        TestFour2.liquid();
        TestFour2.liquor();
        TestFour2.limitation();
        TestFour2.literature();
        TestFour2.lively();
        TestFour2.lime();
        TestFour2.lightning();
        TestFour2.lion();
        TestFour2.liner();
        TestFour2.coach();
        TestFour2.likely();
        TestFour2.coal();
        TestFour2.like();
        TestFour2.limb();
        TestFour2.literary();
        TestFour2.live();
        TestFour2.likewise();
        TestFour2.linen();
        TestFour7.example();
        TestFour8.computer();
        TestFour3.contemporary();
        TestFour1.characteristic();
        TestFour3.granddaughter();
        TestFour4.transformation();
        TestFour2.civilization();
        TestFour11.theoretical();
        TestFour2.sophisticated();
        TestFour1.statistical();
        TestFour1.nationality();
        TestFour1.superficial();
        TestFour1.sympathetic();
        TestFour2.sightseeing();
        TestFour2.significant();
        TestFour3.maintenance();
        TestFour11.thermometer();
        TestFour2.nevertheless();
        TestFour3.constitution();
        TestFour4.transmission();
        TestFour4.transparent();
        TestFour4.troublesome();
        TestFour4.transportation();
        TestFour4.unconscious();
        TestFour4.undergraduate();
        TestFour4.undoubtedly();
        TestFour4.radioactive();
        TestFour4.recognition();
        TestFour1.substantial();
        TestFour1.surroundings();
        TestFour1.necessarily();
        TestFour2.classification();
        TestFour2.neighbourhood();
        TestFour3.grammatical();
        TestFour3.grandfather();
        TestFour3.grandmother();
        TestFour1.certificate();
        TestFour2.circumstance();
        TestFour3.magnificent();
        TestFour3.manufacture();
        TestFour3.masterpiece();
        TestFour3.calculation();
        TestFour2.loudspeaker();
        TestFour3.construction();
        TestFour2.semiconductor();
        TestFour1.systematical();
        TestFour2.significance();
        TestFour2.circumference();
        TestFour3.manufacturer();
        TestFour3.consumption();
        TestFour7.intellectual();
        TestFour4.electricity();
        TestFour5.preposition();
        TestFour5.professional();
        TestFour5.pronunciation();
        TestFour7.interaction();
        TestFour7.interference();
        TestFour5.practically();
        TestFour4.respectively();
        TestFour6.materialism();
        TestFour6.installation();
        TestFour7.instruction();
        TestFour7.international();
        TestFour7.interpretation();
        TestFour5.probability();
        TestFour5.publication();
        TestFour5.preliminary();
        TestFour5.convenience();
        TestFour6.furthermore();
        TestFour7.interpreter();
        TestFour5.corporation();
        TestFour4.engineering();
        TestFour7.insufficient();
        TestFour4.recommendation();
        TestFour5.correspondent();
        TestFour5.progressive();
        TestFour6.fortunately();
        TestFour7.introduction();
        TestFour7.intentional();
        TestFour7.investigate();
        TestFour4.elimination();
        TestFour7.intelligence();
        TestFour5.preparation();
        TestFour5.pessimistic();
        TestFour5.conventional();
        TestFour4.relationship();
        TestFour6.headquarters();
        TestFour4.refrigerator();
        TestFour6.mathematical();
        TestFour5.proportional();
        TestFour6.measurement();
        TestFour6.institution();
        TestFour5.philosopher();
        TestFour6.mathematics();
        TestFour5.contradiction();
        TestFour4.revolutionary();
        TestFour4.representative();
        TestFour4.reliability();
        TestFour5.satisfactory();
        TestFour5.corresponding();
        TestFour5.handkerchief();
        TestFour4.electronics();
        TestFour8.concentrate();
        TestFour8.complicated();
        TestFour8.composition();
        TestFour8.congratulate();
        TestFour8.consciousness();
        TestFour8.perspective();
        TestFour8.communicate();
        TestFour8.conservation();
        TestFour7.enthusiastic();
        TestFour8.comprehensive();
        TestFour8.conservative();
        TestFour7.participate();
        TestFour8.conjunction();
        TestFour7.exceedingly();
        TestFour7.possibility();
        TestFour9.approximate();
        TestFour9.approximately();
        TestFour8.consequence();
        TestFour9.architecture();
        TestFour9.acceleration();
        TestFour8.operational();
        TestFour8.consideration();
        TestFour9.accommodation();
        TestFour7.investigation();
        TestFour7.experimental();
        TestFour8.opportunity();
        TestFour8.communication();
        TestFour8.concentration();
        TestFour8.consequently();
        TestFour8.considerate();
        TestFour9.alternative();
        TestFour9.appropriate();
        TestFour9.accommodate();
        TestFour8.considerable();
        TestFour9.accordingly();
        TestFour9.achievement();
        TestFour9.acquaintance();
        TestFour8.atmospheric();
        TestFour7.exclusively();
        TestFour7.combination();
        TestFour6.honest();
        TestFour6.herd();
        TestFour6.honey();
        TestFour6.honour();
        TestFour6.honourable();
        TestFour6.hopeful();
        TestFour6.hope();
        TestFour6.hire();
        TestFour6.honesty();
        TestFour6.horn();
        TestFour6.hence();
        TestFour6.healthy();
        TestFour6.honeymoon();
        TestFour6.hedge();
        TestFour6.heroic();
        TestFour6.hopeless();
        TestFour6.heavy();
        TestFour6.horror();
        TestFour6.heel();
        TestFour6.headline();
        TestFour6.hear();
        TestFour6.hell();
        TestFour6.heating();
        TestFour6.hesitate();
        TestFour6.heat();
        TestFour6.heir();
        TestFour6.holy();
        TestFour6.helmet();
        TestFour6.heal();
        TestFour6.helpless();
        TestFour6.heavily();
        TestFour6.hillside();
        TestFour6.hobby();
        TestFour5.probably();
        TestFour5.prior();
        TestFour5.primary();
        TestFour5.proceed();
        TestFour5.prescribe();
        TestFour5.prize();
        TestFour5.procedure();
        TestFour5.profession();
        TestFour5.prefer();
        TestFour5.principle();
        TestFour5.promote();
        TestFour5.prompt();
        TestFour5.pronounce();
        TestFour5.proportion();
        TestFour5.proposal();
        TestFour5.procession();
        TestFour5.preferable();
        TestFour5.prospect();
        TestFour5.pretty();
        TestFour5.primarily();
        TestFour5.proof();
        TestFour5.prevent();
        TestFour5.prohibit();
        TestFour5.prominent();
        TestFour5.primitive();
        TestFour5.pronoun();
        TestFour5.propose();
        TestFour5.prosperous();
        TestFour5.pride();
        TestFour5.prince();
        TestFour5.preference();
        TestFour5.presently();
        TestFour5.principal();
        TestFour5.pretend();
        TestFour5.probable();
        TestFour5.proper();
        TestFour5.prosperity();
        TestFour5.protest();
        TestFour5.prejudice();
        TestFour5.protein();
        TestFour5.provide();
        TestFour5.provided();
        TestFour5.proud();
        TestFour5.privilege();
        TestFour5.prevail();
        TestFour5.presence();
        TestFour5.pet();
        TestFour5.pillar();
        TestFour5.pine();
        TestFour5.physician();
        TestFour5.picnic();
        TestFour5.pulse();
        TestFour5.punch();
        TestFour5.pie();
        TestFour5.phrase();
        TestFour5.purpose();
        TestFour5.pile();
        TestFour5.petroleum();
        TestFour5.pursue();
        TestFour5.pilot();
        TestFour5.pinch();
        TestFour5.pity();
        TestFour5.punctual();
        TestFour5.purchase();
        TestFour5.purse();
        TestFour5.purple();
        TestFour5.provision();
        TestFour5.pioneer();
        TestFour5.pit();
        TestFour5.pitch();
        TestFour5.pill();
        TestFour5.pint();
        TestFour5.punish();
        TestFour5.pierce();
        TestFour5.plantation();
        TestFour5.philosophy();
        TestFour5.plastic();
        TestFour5.plate();
        TestFour5.pillow();
        TestFour5.play();
        TestFour5.phenomenon();
        TestFour5.correction();
        TestFour5.convention();
        TestFour5.correspond();
        TestFour5.conversely();
        TestFour5.contrary();
        TestFour5.corridor();
        TestFour5.cottage();
        TestFour5.plenty();
        TestFour5.costly();
        TestFour5.could();
        TestFour5.council();
        TestFour5.convey();
        TestFour5.cordial();
        TestFour5.political();
        TestFour5.county();
        TestFour5.cooperate();
        TestFour5.court();
        TestFour5.cousin();
        TestFour5.polite();
        TestFour5.politician();
        TestFour5.plural();
        TestFour5.poison();
        TestFour5.plentiful();
        TestFour5.pleasure();
        TestFour5.pond();
        TestFour5.contribute();
        TestFour5.convenient();
        TestFour5.plough();
        TestFour5.politics();
        TestFour5.pollute();
        TestFour5.convince();
        TestFour5.plot();
        TestFour5.coordinate();
        TestFour5.contrast();
        TestFour5.cope();
        TestFour5.polish();
        TestFour5.plunge();
        TestFour5.cord();
        TestFour5.corn();
        TestFour5.cultivate();
        TestFour5.crop();
        TestFour5.creative();
        TestFour5.crush();
        TestFour5.creature();
        TestFour5.crust();
        TestFour5.cube();
        TestFour5.cunning();
        TestFour5.crack();
        TestFour5.crew();
        TestFour5.curiosity();
        TestFour5.craft();
        TestFour5.crude();
        TestFour5.cubic();
        TestFour5.crowd();
        TestFour5.inquiry();
        TestFour5.insect();
        TestFour5.inside();
        TestFour5.cupboard();
        TestFour5.crane();
        TestFour5.crime();
        TestFour5.cricket();
        TestFour5.cripple();
        TestFour5.criticize();
        TestFour5.handful();
        TestFour5.critic();
        TestFour5.handsome();
        TestFour5.handy();
        TestFour5.coward();
        TestFour5.cream();
        TestFour5.happiness();
        TestFour5.criticism();
        TestFour5.crown();
        TestFour5.criminal();
        TestFour5.harden();
        TestFour5.crawl();
        TestFour5.hardship();
        TestFour6.hare();
        TestFour6.harm();
        TestFour5.crisis();
        TestFour6.hazard();
        TestFour6.headache();
        TestFour6.heading();
        TestFour6.harsh();
        TestFour6.hasty();
        TestFour6.hat();
        TestFour6.harness();
        TestFour6.harvest();
        TestFour6.haste();
        TestFour6.hatred();
        TestFour6.harmony();
        TestFour6.hatch();
        TestFour6.hasten();
        TestFour6.harmful();
        TestFour6.hay();
        TestFour6.hawk();
        TestFour4.unexpected();
        TestFour10.fatal();
        TestFour11.diverse();
        TestFour11.dose();
        TestFour11.desire();
        TestFour11.doubt();
        TestFour11.domestic();
        TestFour11.despite();
        TestFour11.doubtful();
        TestFour11.doubtless();
        TestFour11.dorm();
        TestFour11.desert();
        TestFour11.deserve();
        TestFour11.ought();
        TestFour11.disgust();
        TestFour11.disguise();
        TestFour11.displease();
        TestFour11.dependent();
        TestFour11.desirable();
        TestFour11.orphan();
        TestFour11.disorder();
        TestFour11.dishonour();
        TestFour11.disposal();
        TestFour11.oriental();
        TestFour11.dislike();
        TestFour11.dispute();
        TestFour11.dissatisfy();
        TestFour11.dish();
        TestFour11.disturb();
        TestFour11.divorce();
        TestFour11.dissolve();
        TestFour11.deposit();
        TestFour11.distress();
        TestFour11.depress();
        TestFour11.descend();
        TestFour11.otherwise();
        TestFour11.distribute();
        TestFour11.district();
        TestFour11.ditch();
        TestFour11.division();
        TestFour11.ornament();
        TestFour11.departure();
        TestFour11.despair();
        TestFour11.despise();
        TestFour11.dismiss();
        TestFour11.distant();
        TestFour11.dock();
        TestFour11.ounce();
        TestFour11.depend();
        TestFour11.dormitory();
        TestFour11.derive();
        TestFour11.desperate();
        TestFour9.beginning();
        TestFour9.bend();
        TestFour9.beneath();
        TestFour9.beneficial();
        TestFour9.benefit();
        TestFour9.berry();
        TestFour8.baggage();
        TestFour8.bang();
        TestFour9.bat();
        TestFour8.bare();
        TestFour9.bay();
        TestFour9.beam();
        TestFour8.ball();
        TestFour9.beginner();
        TestFour9.behalf();
        TestFour8.balloon();
        TestFour9.bath();
        TestFour9.beard();
        TestFour9.bathe();
        TestFour8.basically();
        TestFour8.bake();
        TestFour8.basin();
        TestFour9.beast();
        TestFour9.believe();
        TestFour9.bell();
        TestFour9.belong();
        TestFour9.beloved();
        TestFour9.belt();
        TestFour8.barn();
        TestFour8.barrel();
        TestFour8.bargain();
        TestFour9.beat();
        TestFour9.better();
        TestFour9.blanket();
        TestFour9.bleed();
        TestFour9.bowl();
        TestFour9.bomb();
        TestFour9.bloom();
        TestFour9.bosom();
        TestFour9.biscuit();
        TestFour9.blade();
        TestFour9.bite();
        TestFour9.blind();
        TestFour9.boil();
        TestFour9.bold();
        TestFour9.blast();
        TestFour9.bore();
        TestFour9.bough();
        TestFour9.bolt();
        TestFour9.besides();
        TestFour9.boat();
        TestFour9.bond();
        TestFour9.bitter();
        TestFour9.bet();
        TestFour9.bitterly();
        TestFour9.beyond();
        TestFour9.betray();
        TestFour9.boast();
        TestFour9.booth();
        TestFour9.bother();
        TestFour9.blaze();
        TestFour9.blow();
        TestFour9.boundary();
        TestFour9.brake();
        TestFour9.blame();
        TestFour9.bike();
        TestFour9.bounce();
        TestFour9.brand();
        TestFour9.blossom();
        TestFour9.biology();
        TestFour9.alphabet();
        TestFour9.annoy();
        TestFour9.alter();
        TestFour9.alloy();
        TestFour9.anxiety();
        TestFour9.American();
        TestFour9.anticipate();
        TestFour9.anxious();
        TestFour9.brandy();
        TestFour9.America();
        TestFour9.breathe();
        TestFour9.brass();
        TestFour9.ampere();
        TestFour9.aluminium();
        TestFour9.analysis();
        TestFour9.amongst();
        TestFour9.breed();
        TestFour9.brief();
        TestFour9.brave();
        TestFour9.alone();
        TestFour9.altitude();
        TestFour9.altogether();
        TestFour9.bridge();
        TestFour9.aloud();
        TestFour9.breadth();
        TestFour9.breeze();
        TestFour9.bright();
        TestFour9.amaze();
        TestFour9.anger();
        TestFour9.alike();
        TestFour9.analyse();
        TestFour9.almost();
        TestFour9.ambition();
        TestFour9.breast();
        TestFour9.amplify();
        TestFour9.among();
        TestFour9.amuse();
        TestFour9.aside();
        TestFour9.aspect();
        TestFour9.appeal();
        TestFour9.arbitrary();
        TestFour9.artistic();
        TestFour9.above();
        TestFour9.absent();
        TestFour9.appetite();
        TestFour9.absolutely();
        TestFour9.abundant();
        TestFour9.academic();
        TestFour9.apology();
        TestFour9.assemble();
        TestFour9.absence();
        TestFour9.arrest();
        TestFour9.arise();
        TestFour9.abstract_();
        TestFour9.arouse();
        TestFour9.abnormal();
        TestFour9.asleep();
        TestFour9.appliance();
        TestFour9.absorb();
        TestFour9.academy();
        TestFour9.arrival();
        TestFour9.Arabian();
        TestFour9.arithmetic();
        TestFour9.appreciate();
        TestFour9.apparatus();
        TestFour9.ashamed();
        TestFour9.apartment();
        TestFour9.approve();
        TestFour9.applicable();
        TestFour9.arrow();
        TestFour9.approval();
        TestFour9.apologize();
        TestFour9.ability();
        TestFour9.able();
        TestFour9.adequate();
        TestFour9.adverb();
        TestFour9.accumulate();
        TestFour9.acre();
        TestFour9.advisable();
        TestFour9.afford();
        TestFour9.afraid();
        TestFour9.ache();
        TestFour9.accord();
        TestFour9.acceptable();
        TestFour9.adventure();
        TestFour9.African();
        TestFour9.advanced();
        TestFour9.accessary();
        TestFour9.accompany();
        TestFour9.affection();
        TestFour9.accuracy();
        TestFour9.Africa();
        TestFour9.aeroplane();
        TestFour9.actually();
        TestFour9.admission();
        TestFour9.accident();
        TestFour9.adjective();
        TestFour9.accustomed();
        TestFour9.accidental();
        TestFour9.accent();
        TestFour9.agency();
        TestFour10.agent();
        TestFour9.acceptance();
        TestFour9.achieve();
        TestFour9.activity();
        TestFour9.acute();
        TestFour9.affair();
        TestFour10.aggressive();
        TestFour10.agony();
        TestFour9.accordance();
        TestFour9.accelerate();
        TestFour10.ago();
        TestFour9.accustom();
        TestFour9.accomplish();
        TestFour10.imaginary();
        TestFour10.aid();
        TestFour10.hurry();
        TestFour10.illness();
        TestFour10.imply();
        TestFour10.imagine();
        TestFour10.incident();
        TestFour10.hostile();
        TestFour10.hunger();
        TestFour10.idiom();
        TestFour10.hostess();
        TestFour10.household();
        TestFour10.illustrate();
        TestFour10.importance();
        TestFour10.ideal();
        TestFour10.hurt();
        TestFour10.ignorant();
        TestFour10.immigrant();
        TestFour10.imitate();
        TestFour10.humble();
        TestFour10.hut();
        TestFour10.important();
        TestFour10.impose();
        TestFour10.impossible();
        TestFour10.impress();
        TestFour10.impression();
        TestFour10.impressive();
        TestFour10.imprison();
        TestFour10.hungry();
        TestFour10.humid();
        TestFour10.hydrogen();
        TestFour10.identical();
        TestFour10.faith();
        TestFour10.fame();
        TestFour10.fearful();
        TestFour10.favourable();
        TestFour10.faculty();
        TestFour10.Fahrenheit();
        TestFour10.famine();
        TestFour10.fault();
        TestFour10.feather();
        TestFour10.indeed();
        TestFour10.faithful();
        TestFour10.indication();
        TestFour10.feasible();
        TestFour10.faulty();
        TestFour10.miner();
        TestFour10.mineral();
        TestFour10.indefinite();
        TestFour10.incorrect();
        TestFour10.increase();
        TestFour10.fasten();
        TestFour10.facility();
        TestFour10.fare();
        TestFour10.factor();
        TestFour10.indicate();
        TestFour10.fatigue();
        TestFour10.minimum();
        TestFour10.minority();
        TestFour10.feast();
        TestFour10.ministry();
        TestFour10.miracle();
        TestFour10.incline();
        TestFour10.faint();
        TestFour10.indignant();
        TestFour10.indirect();
        TestFour10.miserable();
        TestFour10.fear();
        TestFour10.familiar();
        TestFour10.favourite();
        TestFour10.farewell();
        TestFour10.missing();
        TestFour10.mixture();
        TestFour10.moan();
        TestFour10.fifth();
        TestFour10.mislead();
        TestFour10.mistress();
        TestFour10.fist();
        TestFour10.fit();
        TestFour10.mist();
        TestFour10.feeble();
        TestFour10.festival();
        TestFour10.flame();
        TestFour10.missile();
        TestFour10.flash();
        TestFour10.fertilizer();
        TestFour10.flare();
        TestFour10.mission();
        TestFour10.fetch();
        TestFour10.Mister();
        TestFour10.modest();
        TestFour10.modern();
        TestFour10.federal();
        TestFour10.fellow();
        TestFour10.fiction();
        TestFour10.fibre();
        TestFour10.moisture();
        TestFour10.mistake();
        TestFour10.molecule();
        TestFour10.fever();
        TestFour10.fierce();
        TestFour10.moist();
        TestFour10.moderate();
        TestFour10.fee();
        TestFour10.moment();
        TestFour10.fertile();
        TestFour10.injury();
        TestFour10.curtain();
        TestFour10.infer();
        TestFour10.injection();
        TestFour11.daring();
        TestFour11.dash();
        TestFour11.dawn();
        TestFour11.deaf();
        TestFour10.infect();
        TestFour10.flock();
        TestFour10.influence();
        TestFour10.inn();
        TestFour11.damage();
        TestFour10.inherit();
        TestFour10.dairy();
        TestFour10.fluent();
        TestFour10.inferior();
        TestFour11.damp();
        TestFour10.flesh();
        TestFour10.curious();
        TestFour10.curse();
        TestFour10.customer();
        TestFour10.flourish();
        TestFour10.curve();
        TestFour11.dark();
        TestFour10.inform();
        TestFour10.cycle();
        TestFour10.flight();
        TestFour10.flow();
        TestFour10.initial();
        TestFour10.flood();
        TestFour10.cushion();
        TestFour10.inhabit();
        TestFour10.curl();
        TestFour10.daily();
        TestFour11.dam();
        TestFour11.darling();
        TestFour10.infant();
        TestFour10.inhabitant();
        TestFour10.fleet();
        TestFour10.flexible();
        TestFour10.inevitable();
        TestFour10.flavour();
        TestFour11.debt();
        TestFour11.decrease();
        TestFour11.deduce();
        TestFour11.defect();
        TestFour11.delivery();
        TestFour11.dense();
        TestFour11.density();
        TestFour11.decay();
        TestFour11.decorate();
        TestFour11.define();
        TestFour11.definitely();
        TestFour11.delicate();
        TestFour11.defeat();
        TestFour11.defend();
        TestFour11.deepen();
        TestFour11.defence();
        TestFour11.definition();
        TestFour11.demand();
        TestFour11.democracy();
        TestFour11.deed();
        TestFour11.definite();
        TestFour11.delegation();
        TestFour11.delight();
        TestFour11.deliver();
        TestFour11.depart();
        TestFour11.deceive();
        TestFour11.decent();
        TestFour11.demonstrate();
        TestFour10.agriculture();
        TestFour10.implication();
        TestFour10.industrialize();
        TestFour11.destruction();
        TestFour11.distribution();
        TestFour11.distinction();
        TestFour10.misunderstand();
        TestFour10.fashionable();
        TestFour10.indispensable();
        TestFour11.distinguish();
        TestFour10.increasingly();
        TestFour10.illustration();
        TestFour10.influential();
        TestFour11.dew();
        TestFour11.drag();
        TestFour11.drawer();
        TestFour11.devise();
        TestFour11.dread();
        TestFour11.drop();
        TestFour11.devote();
        TestFour11.drawing();
        TestFour8.assembly();
        TestFour8.conscience();
        TestFour8.associate();
        TestFour8.attend();
        TestFour8.attention();
        TestFour8.attentive();
        TestFour8.attitude();
        TestFour8.attraction();
        TestFour8.conquest();
        TestFour8.attempt();
        TestFour8.auto();
        TestFour8.attractive();
        TestFour8.automation();
        TestFour8.automobile();
        TestFour8.confusion();
        TestFour8.attack();
        TestFour8.conscious();
        TestFour8.aural();
        TestFour8.autumn();
        TestFour8.congress();
        TestFour8.consent();
        TestFour8.auxiliary();
        TestFour8.aviation();
        TestFour8.Atlantic();
        TestFour8.awake();
        TestFour8.astonish();
        TestFour8.aware();
        TestFour8.assignment();
        TestFour8.astronaut();
        TestFour8.awkward();
        TestFour8.assess();
        TestFour8.axis();
        TestFour8.atomic();
        TestFour8.assume();
        TestFour8.assure();
        TestFour8.bacteria();
        TestFour8.badminton();
        TestFour8.bag();
        TestFour8.attract();
        TestFour8.award();
        TestFour8.confuse();
        TestFour6.mature();
        TestFour6.mention();
        TestFour6.maximum();
        TestFour6.medium();
        TestFour6.melon();
        TestFour6.mental();
        TestFour6.mercury();
        TestFour6.merchant();
        TestFour6.mercy();
        TestFour6.meadow();
        TestFour6.mere();
        TestFour6.mechanics();
        TestFour6.mend();
        TestFour6.merely();
        TestFour6.merry();
        TestFour6.meantime();
        TestFour6.measurable();
        TestFour6.metric();
        TestFour6.material();
        TestFour6.measure();
        TestFour6.microscope();
        TestFour6.midst();
        TestFour6.means();
        TestFour6.memorial();
        TestFour6.military();
        TestFour6.mild();
        TestFour6.mill();
        TestFour6.millimetre();
        TestFour6.mate();
        TestFour6.fruitful();
        TestFour6.fry();
        TestFour6.forecast();
        TestFour6.fortunate();
        TestFour6.fuel();
        TestFour6.foundation();
        TestFour6.fulfil();
        TestFour6.fun();
        TestFour6.fund();
        TestFour6.folk();
        TestFour6.formula();
        TestFour6.following();
        TestFour6.foolish();
        TestFour6.fortnight();
        TestFour6.fourth();
        TestFour6.frank();
        TestFour6.freight();
        TestFour6.frequent();
        TestFour6.fridge();
        TestFour6.fog();
        TestFour6.forever();
        TestFour6.forehead();
        TestFour6.formation();
        TestFour6.forth();
        TestFour6.fountain();
        TestFour6.frequently();
        TestFour6.frighten();
        TestFour6.fond();
        TestFour6.foreign();
        TestFour6.fold();
        TestFour6.foreigner();
        TestFour6.fortune();
        TestFour6.friction();
        TestFour6.frog();
        TestFour6.frost();
        TestFour6.frown();
        TestFour6.for_();
        TestFour6.foremost();
        TestFour6.forgive();
        TestFour6.forty();
        TestFour6.gasp();
        TestFour7.intention();
        TestFour7.insult();
        TestFour7.insurance();
        TestFour6.gallery();
        TestFour6.gap();
        TestFour6.gather();
        TestFour7.intend();
        TestFour6.institute();
        TestFour6.garage();
        TestFour6.gaseous();
        TestFour6.gauge();
        TestFour7.invisible();
        TestFour6.instantly();
        TestFour6.furnish();
        TestFour6.inspire();
        TestFour6.instinct();
        TestFour6.instruct();
        TestFour7.interpret();
        TestFour6.gasoline();
        TestFour7.intensity();
        TestFour7.interfere();
        TestFour7.intensive();
        TestFour7.introduce();
        TestFour6.furious();
        TestFour6.furnace();
        TestFour7.intense();

        System.out.println(System.getProperty("user.dir"));
        String filePath = System.getProperty("user.dir").concat("/doc/a4.txt");
        BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(filePath)));



    }


    @SneakyThrows
    @Test
    public  void test2848() {

        String str = "23456";
        System.out.println(System.getProperty("user.dir"));
        String filePath = System.getProperty("user.dir").concat("/doc/a4.txt");
        BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(filePath)));
        String line = null;
        List<JSONObject> jsonObjectList = new ArrayList<>();
        StringBuffer teBuff = null;
        StringBuffer peBuff = null;
        StringBuffer pcBuff = null;
        JSONObject json = null;
        while ((line = br.readLine()) != null){
            line = line.trim();

            if(line.contains("Lesson ")){


                if(json == null){
                    json = new JSONObject();
                }else{
                    json.put("pc", pcBuff);
                    pcBuff = null;
                    jsonObjectList.add(json);
                    json = new JSONObject();
                }
            }

            if(line.contains("Lesson ")){
                teBuff = new StringBuffer();
            }

            if(line.contains("First listen")){
                json.put("te", teBuff.toString());
                teBuff = null;
                peBuff = new StringBuffer();
            }

            if(line.contains("生词和短语")){
                json.put("pe", peBuff.toString());
                peBuff = null;
            }

            if(line.contains("参考译文")){
                pcBuff = new StringBuffer();
            }

            if(teBuff != null){
                teBuff.append(line);
            }

            if(peBuff != null){
                if(!line.contains("First listen") && !line.contains("听录音，")){
                    if(!((line.startsWith("W") || line.startsWith("H")) && line.endsWith("?"))){
                        peBuff.append(line);
                    }
                }

            }

            if(pcBuff != null){
                pcBuff.append(line);
            }

        }


        for (int i = 1; i <= jsonObjectList.size(); i++) {

            JSONObject e = jsonObjectList.get(i - 1);

            String te = e.getString("te");
            //String tc = e.getString("tc");
            String pe = e.getString("pe");
            String pc = e.getString("pc");

            String aa = "/**\n" +
                    " * @te "+te+"\n" +
                    " * @pe "+pe+"\n" +
              //      " * @tc "+tc+"\n" +
                    " * @pc "+pc+"\n" +
                    " */\n" +
                    "public static void lesson"+i+"(){};";
            log.info("\n");
            log.info(aa);
        }

    }

    @SneakyThrows
    @Test
    public  void methodListFour() {

        List<Method> methods = new ArrayList<>();
        for (int i = 1; i <= 11; i++) {
            Class<?> aClass = Class.forName("com.words.TestFour" + i);
            methods.addAll(Arrays.asList(aClass.getDeclaredMethods()));
        }

        Map<String, Method> methodMap = methods.stream().collect(Collectors.toMap(Method::getName, e -> e));

        String filePath = System.getProperty("user.dir").concat("/doc/a3");
        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(new FileInputStream(filePath)));
        String line = null;
        while ((line = bufferedReader.readLine()) != null){

            try{



                String substring = line.substring(line.indexOf(".") + 1, line.indexOf("("));
                Method method = methodMap.get(substring);
                if(method != null){
                    log.info(method.getDeclaringClass().getSimpleName() + "." + method.getName() + "();");
                }
            }catch (StringIndexOutOfBoundsException e){
            }

        }
    }


    @SneakyThrows
    public static void main(String[] args) {
        int a = 3;
        System.out.println(65 & 64);
        System.out.println(0 & 1);
        System.out.println(0 & 2);
        System.out.println(0 & 3);
    }

    @Test
    public void main2() {
        String filePath = System.getProperty("user.dir").concat("/temp/lock.txt");
        try (FileChannel open = FileChannel.open(Path.of(filePath), StandardOpenOption.WRITE)){
            FileLock fileLock = open.lock();
            FileLock fileLock1 = open.tryLock();
            fileLock1.release();
            Channel channel = fileLock.acquiredBy();
            ThirdVolume.test1();

        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}